"""PINE IntelligenceCase relational tables

Revision ID: 0006_pine_intelligence_case
Revises: 0005_peacock_crawler
Create Date: 2026-08-12
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0006_pine_intelligence_case"
down_revision: Union[str, None] = "0005_peacock_crawler"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intelligence_cases',
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('cost_usd_micros', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.String(length=36), nullable=True),
    sa.Column('strategic_run_id', sa.String(length=36), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_intelligence_cases_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_intelligence_cases_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_intelligence_cases_website_id_websites'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_intelligence_cases_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_cases'))
    )
    op.create_index(op.f('ix_intelligence_cases_created_by'), 'intelligence_cases', ['created_by'], unique=False)
    op.create_index(op.f('ix_intelligence_cases_organisation_id'), 'intelligence_cases', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_cases_status'), 'intelligence_cases', ['status'], unique=False)
    op.create_index(op.f('ix_intelligence_cases_strategic_run_id'), 'intelligence_cases', ['strategic_run_id'], unique=False)
    op.create_index(op.f('ix_intelligence_cases_website_id'), 'intelligence_cases', ['website_id'], unique=False)
    op.create_index(op.f('ix_intelligence_cases_workspace_id'), 'intelligence_cases', ['workspace_id'], unique=False)
    op.create_table('intelligence_case_agent_findings',
    sa.Column('agent_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_llm_derived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intelligence_cases.id'], name=op.f('fk_intelligence_case_agent_findings_case_id_intelligence_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_intelligence_case_agent_findings_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_intelligence_case_agent_findings_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_case_agent_findings'))
    )
    op.create_index(op.f('ix_intelligence_case_agent_findings_agent_name'), 'intelligence_case_agent_findings', ['agent_name'], unique=False)
    op.create_index(op.f('ix_intelligence_case_agent_findings_case_id'), 'intelligence_case_agent_findings', ['case_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_agent_findings_organisation_id'), 'intelligence_case_agent_findings', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_agent_findings_role'), 'intelligence_case_agent_findings', ['role'], unique=False)
    op.create_index(op.f('ix_intelligence_case_agent_findings_status'), 'intelligence_case_agent_findings', ['status'], unique=False)
    op.create_index(op.f('ix_intelligence_case_agent_findings_workspace_id'), 'intelligence_case_agent_findings', ['workspace_id'], unique=False)
    op.create_table('intelligence_case_assumptions',
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_if_wrong', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intelligence_cases.id'], name=op.f('fk_intelligence_case_assumptions_case_id_intelligence_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_intelligence_case_assumptions_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_intelligence_case_assumptions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_case_assumptions'))
    )
    op.create_index(op.f('ix_intelligence_case_assumptions_case_id'), 'intelligence_case_assumptions', ['case_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_assumptions_organisation_id'), 'intelligence_case_assumptions', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_assumptions_status'), 'intelligence_case_assumptions', ['status'], unique=False)
    op.create_index(op.f('ix_intelligence_case_assumptions_workspace_id'), 'intelligence_case_assumptions', ['workspace_id'], unique=False)
    op.create_table('intelligence_case_context_items',
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('tokens_estimate', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intelligence_cases.id'], name=op.f('fk_intelligence_case_context_items_case_id_intelligence_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_intelligence_case_context_items_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_intelligence_case_context_items_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_case_context_items'))
    )
    op.create_index(op.f('ix_intelligence_case_context_items_case_id'), 'intelligence_case_context_items', ['case_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_context_items_kind'), 'intelligence_case_context_items', ['kind'], unique=False)
    op.create_index(op.f('ix_intelligence_case_context_items_organisation_id'), 'intelligence_case_context_items', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_context_items_status'), 'intelligence_case_context_items', ['status'], unique=False)
    op.create_index(op.f('ix_intelligence_case_context_items_workspace_id'), 'intelligence_case_context_items', ['workspace_id'], unique=False)
    op.create_table('intelligence_case_contradictions',
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('challenge', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('unresolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intelligence_cases.id'], name=op.f('fk_intelligence_case_contradictions_case_id_intelligence_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_intelligence_case_contradictions_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_intelligence_case_contradictions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_case_contradictions'))
    )
    op.create_index(op.f('ix_intelligence_case_contradictions_case_id'), 'intelligence_case_contradictions', ['case_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_contradictions_organisation_id'), 'intelligence_case_contradictions', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_contradictions_severity'), 'intelligence_case_contradictions', ['severity'], unique=False)
    op.create_index(op.f('ix_intelligence_case_contradictions_status'), 'intelligence_case_contradictions', ['status'], unique=False)
    op.create_index(op.f('ix_intelligence_case_contradictions_workspace_id'), 'intelligence_case_contradictions', ['workspace_id'], unique=False)
    op.create_table('intelligence_case_evidence',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intelligence_cases.id'], name=op.f('fk_intelligence_case_evidence_case_id_intelligence_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_intelligence_case_evidence_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_intelligence_case_evidence_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_case_evidence'))
    )
    op.create_index(op.f('ix_intelligence_case_evidence_case_id'), 'intelligence_case_evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_evidence_code'), 'intelligence_case_evidence', ['code'], unique=False)
    op.create_index(op.f('ix_intelligence_case_evidence_kind'), 'intelligence_case_evidence', ['kind'], unique=False)
    op.create_index(op.f('ix_intelligence_case_evidence_organisation_id'), 'intelligence_case_evidence', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_evidence_status'), 'intelligence_case_evidence', ['status'], unique=False)
    op.create_index(op.f('ix_intelligence_case_evidence_workspace_id'), 'intelligence_case_evidence', ['workspace_id'], unique=False)
    op.create_table('intelligence_case_hypotheses',
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status_label', sa.String(length=32), nullable=False),
    sa.Column('supporting_evidence_codes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intelligence_cases.id'], name=op.f('fk_intelligence_case_hypotheses_case_id_intelligence_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_intelligence_case_hypotheses_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_intelligence_case_hypotheses_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_case_hypotheses'))
    )
    op.create_index(op.f('ix_intelligence_case_hypotheses_case_id'), 'intelligence_case_hypotheses', ['case_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_hypotheses_organisation_id'), 'intelligence_case_hypotheses', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_hypotheses_status'), 'intelligence_case_hypotheses', ['status'], unique=False)
    op.create_index(op.f('ix_intelligence_case_hypotheses_status_label'), 'intelligence_case_hypotheses', ['status_label'], unique=False)
    op.create_index(op.f('ix_intelligence_case_hypotheses_workspace_id'), 'intelligence_case_hypotheses', ['workspace_id'], unique=False)
    op.create_table('intelligence_case_models_used',
    sa.Column('provider_code', sa.String(length=64), nullable=False),
    sa.Column('model_code', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('cost_usd_micros', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intelligence_cases.id'], name=op.f('fk_intelligence_case_models_used_case_id_intelligence_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['ai_provider_models.id'], name=op.f('fk_intelligence_case_models_used_model_id_ai_provider_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_intelligence_case_models_used_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], name=op.f('fk_intelligence_case_models_used_provider_id_ai_providers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_intelligence_case_models_used_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_case_models_used'))
    )
    op.create_index(op.f('ix_intelligence_case_models_used_case_id'), 'intelligence_case_models_used', ['case_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_models_used_model_id'), 'intelligence_case_models_used', ['model_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_models_used_organisation_id'), 'intelligence_case_models_used', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_models_used_provider_code'), 'intelligence_case_models_used', ['provider_code'], unique=False)
    op.create_index(op.f('ix_intelligence_case_models_used_provider_id'), 'intelligence_case_models_used', ['provider_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_models_used_role'), 'intelligence_case_models_used', ['role'], unique=False)
    op.create_index(op.f('ix_intelligence_case_models_used_status'), 'intelligence_case_models_used', ['status'], unique=False)
    op.create_index(op.f('ix_intelligence_case_models_used_workspace_id'), 'intelligence_case_models_used', ['workspace_id'], unique=False)
    op.create_table('intelligence_case_observations',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intelligence_cases.id'], name=op.f('fk_intelligence_case_observations_case_id_intelligence_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_intelligence_case_observations_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_intelligence_case_observations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_case_observations'))
    )
    op.create_index(op.f('ix_intelligence_case_observations_case_id'), 'intelligence_case_observations', ['case_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_observations_code'), 'intelligence_case_observations', ['code'], unique=False)
    op.create_index(op.f('ix_intelligence_case_observations_organisation_id'), 'intelligence_case_observations', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_observations_status'), 'intelligence_case_observations', ['status'], unique=False)
    op.create_index(op.f('ix_intelligence_case_observations_workspace_id'), 'intelligence_case_observations', ['workspace_id'], unique=False)
    op.create_table('intelligence_case_opportunities',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact', sa.Float(), nullable=False),
    sa.Column('effort', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intelligence_cases.id'], name=op.f('fk_intelligence_case_opportunities_case_id_intelligence_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_intelligence_case_opportunities_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_intelligence_case_opportunities_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_case_opportunities'))
    )
    op.create_index(op.f('ix_intelligence_case_opportunities_case_id'), 'intelligence_case_opportunities', ['case_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_opportunities_organisation_id'), 'intelligence_case_opportunities', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_opportunities_status'), 'intelligence_case_opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_intelligence_case_opportunities_workspace_id'), 'intelligence_case_opportunities', ['workspace_id'], unique=False)
    op.create_table('intelligence_case_risks',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('likelihood', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intelligence_cases.id'], name=op.f('fk_intelligence_case_risks_case_id_intelligence_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_intelligence_case_risks_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_intelligence_case_risks_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_case_risks'))
    )
    op.create_index(op.f('ix_intelligence_case_risks_case_id'), 'intelligence_case_risks', ['case_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_risks_organisation_id'), 'intelligence_case_risks', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_risks_severity'), 'intelligence_case_risks', ['severity'], unique=False)
    op.create_index(op.f('ix_intelligence_case_risks_status'), 'intelligence_case_risks', ['status'], unique=False)
    op.create_index(op.f('ix_intelligence_case_risks_workspace_id'), 'intelligence_case_risks', ['workspace_id'], unique=False)
    op.create_table('intelligence_case_tools_used',
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('tool_version', sa.String(length=64), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('invocation_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intelligence_cases.id'], name=op.f('fk_intelligence_case_tools_used_case_id_intelligence_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_intelligence_case_tools_used_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_intelligence_case_tools_used_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_case_tools_used'))
    )
    op.create_index(op.f('ix_intelligence_case_tools_used_case_id'), 'intelligence_case_tools_used', ['case_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_tools_used_organisation_id'), 'intelligence_case_tools_used', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_tools_used_status'), 'intelligence_case_tools_used', ['status'], unique=False)
    op.create_index(op.f('ix_intelligence_case_tools_used_tool_name'), 'intelligence_case_tools_used', ['tool_name'], unique=False)
    op.create_index(op.f('ix_intelligence_case_tools_used_workspace_id'), 'intelligence_case_tools_used', ['workspace_id'], unique=False)
    op.create_table('intelligence_case_unknowns',
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('impact_if_unknown', sa.Text(), nullable=True),
    sa.Column('suggested_investigation', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intelligence_cases.id'], name=op.f('fk_intelligence_case_unknowns_case_id_intelligence_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_intelligence_case_unknowns_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_intelligence_case_unknowns_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_case_unknowns'))
    )
    op.create_index(op.f('ix_intelligence_case_unknowns_case_id'), 'intelligence_case_unknowns', ['case_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_unknowns_organisation_id'), 'intelligence_case_unknowns', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_unknowns_status'), 'intelligence_case_unknowns', ['status'], unique=False)
    op.create_index(op.f('ix_intelligence_case_unknowns_workspace_id'), 'intelligence_case_unknowns', ['workspace_id'], unique=False)
    op.create_table('intelligence_case_agent_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intelligence_cases.id'], name=op.f('fk_intelligence_case_agent_claims_case_id_intelligence_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['intelligence_case_agent_findings.id'], name=op.f('fk_intelligence_case_agent_claims_finding_id_intelligence_case_agent_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_intelligence_case_agent_claims_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_intelligence_case_agent_claims_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_case_agent_claims'))
    )
    op.create_index(op.f('ix_intelligence_case_agent_claims_case_id'), 'intelligence_case_agent_claims', ['case_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_agent_claims_finding_id'), 'intelligence_case_agent_claims', ['finding_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_agent_claims_organisation_id'), 'intelligence_case_agent_claims', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_agent_claims_workspace_id'), 'intelligence_case_agent_claims', ['workspace_id'], unique=False)
    op.create_table('intelligence_case_evidence_urls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intelligence_cases.id'], name=op.f('fk_intelligence_case_evidence_urls_case_id_intelligence_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['intelligence_case_evidence.id'], name=op.f('fk_intelligence_case_evidence_urls_evidence_id_intelligence_case_evidence'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_intelligence_case_evidence_urls_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_intelligence_case_evidence_urls_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_case_evidence_urls')),
    sa.UniqueConstraint('evidence_id', 'url', name=op.f('uq_intelligence_case_evidence_urls_evidence_id'))
    )
    op.create_index(op.f('ix_intelligence_case_evidence_urls_case_id'), 'intelligence_case_evidence_urls', ['case_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_evidence_urls_evidence_id'), 'intelligence_case_evidence_urls', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_evidence_urls_organisation_id'), 'intelligence_case_evidence_urls', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_evidence_urls_workspace_id'), 'intelligence_case_evidence_urls', ['workspace_id'], unique=False)
    op.create_table('intelligence_case_recommendations',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('impact', sa.Float(), nullable=False),
    sa.Column('effort', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('depends_on_inference', sa.Boolean(), nullable=False),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('learning_recommendation_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intelligence_cases.id'], name=op.f('fk_intelligence_case_recommendations_case_id_intelligence_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learning_recommendation_id'], ['recommendations.id'], name=op.f('fk_intelligence_case_recommendations_learning_recommendation_id_recommendations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_intelligence_case_recommendations_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_intelligence_case_recommendations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_case_recommendations'))
    )
    op.create_index(op.f('ix_intelligence_case_recommendations_case_id'), 'intelligence_case_recommendations', ['case_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_recommendations_learning_recommendation_id'), 'intelligence_case_recommendations', ['learning_recommendation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_recommendations_organisation_id'), 'intelligence_case_recommendations', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_recommendations_priority'), 'intelligence_case_recommendations', ['priority'], unique=False)
    op.create_index(op.f('ix_intelligence_case_recommendations_status'), 'intelligence_case_recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_intelligence_case_recommendations_workspace_id'), 'intelligence_case_recommendations', ['workspace_id'], unique=False)
    op.create_table('intelligence_case_recommendation_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_code', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intelligence_cases.id'], name=op.f('fk_intelligence_case_recommendation_evidence_case_id_intelligence_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_intelligence_case_recommendation_evidence_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['intelligence_case_recommendations.id'], name=op.f('fk_intelligence_case_recommendation_evidence_recommendation_id_intelligence_case_recommendations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_intelligence_case_recommendation_evidence_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_case_recommendation_evidence')),
    sa.UniqueConstraint('recommendation_id', 'evidence_code', name=op.f('uq_intelligence_case_recommendation_evidence_recommendation_id'))
    )
    op.create_index(op.f('ix_intelligence_case_recommendation_evidence_case_id'), 'intelligence_case_recommendation_evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_recommendation_evidence_organisation_id'), 'intelligence_case_recommendation_evidence', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_recommendation_evidence_recommendation_id'), 'intelligence_case_recommendation_evidence', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_case_recommendation_evidence_workspace_id'), 'intelligence_case_recommendation_evidence', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intelligence_case_recommendation_evidence_workspace_id'), table_name='intelligence_case_recommendation_evidence')
    op.drop_index(op.f('ix_intelligence_case_recommendation_evidence_recommendation_id'), table_name='intelligence_case_recommendation_evidence')
    op.drop_index(op.f('ix_intelligence_case_recommendation_evidence_organisation_id'), table_name='intelligence_case_recommendation_evidence')
    op.drop_index(op.f('ix_intelligence_case_recommendation_evidence_case_id'), table_name='intelligence_case_recommendation_evidence')
    op.drop_table('intelligence_case_recommendation_evidence')
    op.drop_index(op.f('ix_intelligence_case_recommendations_workspace_id'), table_name='intelligence_case_recommendations')
    op.drop_index(op.f('ix_intelligence_case_recommendations_status'), table_name='intelligence_case_recommendations')
    op.drop_index(op.f('ix_intelligence_case_recommendations_priority'), table_name='intelligence_case_recommendations')
    op.drop_index(op.f('ix_intelligence_case_recommendations_organisation_id'), table_name='intelligence_case_recommendations')
    op.drop_index(op.f('ix_intelligence_case_recommendations_learning_recommendation_id'), table_name='intelligence_case_recommendations')
    op.drop_index(op.f('ix_intelligence_case_recommendations_case_id'), table_name='intelligence_case_recommendations')
    op.drop_table('intelligence_case_recommendations')
    op.drop_index(op.f('ix_intelligence_case_evidence_urls_workspace_id'), table_name='intelligence_case_evidence_urls')
    op.drop_index(op.f('ix_intelligence_case_evidence_urls_organisation_id'), table_name='intelligence_case_evidence_urls')
    op.drop_index(op.f('ix_intelligence_case_evidence_urls_evidence_id'), table_name='intelligence_case_evidence_urls')
    op.drop_index(op.f('ix_intelligence_case_evidence_urls_case_id'), table_name='intelligence_case_evidence_urls')
    op.drop_table('intelligence_case_evidence_urls')
    op.drop_index(op.f('ix_intelligence_case_agent_claims_workspace_id'), table_name='intelligence_case_agent_claims')
    op.drop_index(op.f('ix_intelligence_case_agent_claims_organisation_id'), table_name='intelligence_case_agent_claims')
    op.drop_index(op.f('ix_intelligence_case_agent_claims_finding_id'), table_name='intelligence_case_agent_claims')
    op.drop_index(op.f('ix_intelligence_case_agent_claims_case_id'), table_name='intelligence_case_agent_claims')
    op.drop_table('intelligence_case_agent_claims')
    op.drop_index(op.f('ix_intelligence_case_unknowns_workspace_id'), table_name='intelligence_case_unknowns')
    op.drop_index(op.f('ix_intelligence_case_unknowns_status'), table_name='intelligence_case_unknowns')
    op.drop_index(op.f('ix_intelligence_case_unknowns_organisation_id'), table_name='intelligence_case_unknowns')
    op.drop_index(op.f('ix_intelligence_case_unknowns_case_id'), table_name='intelligence_case_unknowns')
    op.drop_table('intelligence_case_unknowns')
    op.drop_index(op.f('ix_intelligence_case_tools_used_workspace_id'), table_name='intelligence_case_tools_used')
    op.drop_index(op.f('ix_intelligence_case_tools_used_tool_name'), table_name='intelligence_case_tools_used')
    op.drop_index(op.f('ix_intelligence_case_tools_used_status'), table_name='intelligence_case_tools_used')
    op.drop_index(op.f('ix_intelligence_case_tools_used_organisation_id'), table_name='intelligence_case_tools_used')
    op.drop_index(op.f('ix_intelligence_case_tools_used_case_id'), table_name='intelligence_case_tools_used')
    op.drop_table('intelligence_case_tools_used')
    op.drop_index(op.f('ix_intelligence_case_risks_workspace_id'), table_name='intelligence_case_risks')
    op.drop_index(op.f('ix_intelligence_case_risks_status'), table_name='intelligence_case_risks')
    op.drop_index(op.f('ix_intelligence_case_risks_severity'), table_name='intelligence_case_risks')
    op.drop_index(op.f('ix_intelligence_case_risks_organisation_id'), table_name='intelligence_case_risks')
    op.drop_index(op.f('ix_intelligence_case_risks_case_id'), table_name='intelligence_case_risks')
    op.drop_table('intelligence_case_risks')
    op.drop_index(op.f('ix_intelligence_case_opportunities_workspace_id'), table_name='intelligence_case_opportunities')
    op.drop_index(op.f('ix_intelligence_case_opportunities_status'), table_name='intelligence_case_opportunities')
    op.drop_index(op.f('ix_intelligence_case_opportunities_organisation_id'), table_name='intelligence_case_opportunities')
    op.drop_index(op.f('ix_intelligence_case_opportunities_case_id'), table_name='intelligence_case_opportunities')
    op.drop_table('intelligence_case_opportunities')
    op.drop_index(op.f('ix_intelligence_case_observations_workspace_id'), table_name='intelligence_case_observations')
    op.drop_index(op.f('ix_intelligence_case_observations_status'), table_name='intelligence_case_observations')
    op.drop_index(op.f('ix_intelligence_case_observations_organisation_id'), table_name='intelligence_case_observations')
    op.drop_index(op.f('ix_intelligence_case_observations_code'), table_name='intelligence_case_observations')
    op.drop_index(op.f('ix_intelligence_case_observations_case_id'), table_name='intelligence_case_observations')
    op.drop_table('intelligence_case_observations')
    op.drop_index(op.f('ix_intelligence_case_models_used_workspace_id'), table_name='intelligence_case_models_used')
    op.drop_index(op.f('ix_intelligence_case_models_used_status'), table_name='intelligence_case_models_used')
    op.drop_index(op.f('ix_intelligence_case_models_used_role'), table_name='intelligence_case_models_used')
    op.drop_index(op.f('ix_intelligence_case_models_used_provider_id'), table_name='intelligence_case_models_used')
    op.drop_index(op.f('ix_intelligence_case_models_used_provider_code'), table_name='intelligence_case_models_used')
    op.drop_index(op.f('ix_intelligence_case_models_used_organisation_id'), table_name='intelligence_case_models_used')
    op.drop_index(op.f('ix_intelligence_case_models_used_model_id'), table_name='intelligence_case_models_used')
    op.drop_index(op.f('ix_intelligence_case_models_used_case_id'), table_name='intelligence_case_models_used')
    op.drop_table('intelligence_case_models_used')
    op.drop_index(op.f('ix_intelligence_case_hypotheses_workspace_id'), table_name='intelligence_case_hypotheses')
    op.drop_index(op.f('ix_intelligence_case_hypotheses_status_label'), table_name='intelligence_case_hypotheses')
    op.drop_index(op.f('ix_intelligence_case_hypotheses_status'), table_name='intelligence_case_hypotheses')
    op.drop_index(op.f('ix_intelligence_case_hypotheses_organisation_id'), table_name='intelligence_case_hypotheses')
    op.drop_index(op.f('ix_intelligence_case_hypotheses_case_id'), table_name='intelligence_case_hypotheses')
    op.drop_table('intelligence_case_hypotheses')
    op.drop_index(op.f('ix_intelligence_case_evidence_workspace_id'), table_name='intelligence_case_evidence')
    op.drop_index(op.f('ix_intelligence_case_evidence_status'), table_name='intelligence_case_evidence')
    op.drop_index(op.f('ix_intelligence_case_evidence_organisation_id'), table_name='intelligence_case_evidence')
    op.drop_index(op.f('ix_intelligence_case_evidence_kind'), table_name='intelligence_case_evidence')
    op.drop_index(op.f('ix_intelligence_case_evidence_code'), table_name='intelligence_case_evidence')
    op.drop_index(op.f('ix_intelligence_case_evidence_case_id'), table_name='intelligence_case_evidence')
    op.drop_table('intelligence_case_evidence')
    op.drop_index(op.f('ix_intelligence_case_contradictions_workspace_id'), table_name='intelligence_case_contradictions')
    op.drop_index(op.f('ix_intelligence_case_contradictions_status'), table_name='intelligence_case_contradictions')
    op.drop_index(op.f('ix_intelligence_case_contradictions_severity'), table_name='intelligence_case_contradictions')
    op.drop_index(op.f('ix_intelligence_case_contradictions_organisation_id'), table_name='intelligence_case_contradictions')
    op.drop_index(op.f('ix_intelligence_case_contradictions_case_id'), table_name='intelligence_case_contradictions')
    op.drop_table('intelligence_case_contradictions')
    op.drop_index(op.f('ix_intelligence_case_context_items_workspace_id'), table_name='intelligence_case_context_items')
    op.drop_index(op.f('ix_intelligence_case_context_items_status'), table_name='intelligence_case_context_items')
    op.drop_index(op.f('ix_intelligence_case_context_items_organisation_id'), table_name='intelligence_case_context_items')
    op.drop_index(op.f('ix_intelligence_case_context_items_kind'), table_name='intelligence_case_context_items')
    op.drop_index(op.f('ix_intelligence_case_context_items_case_id'), table_name='intelligence_case_context_items')
    op.drop_table('intelligence_case_context_items')
    op.drop_index(op.f('ix_intelligence_case_assumptions_workspace_id'), table_name='intelligence_case_assumptions')
    op.drop_index(op.f('ix_intelligence_case_assumptions_status'), table_name='intelligence_case_assumptions')
    op.drop_index(op.f('ix_intelligence_case_assumptions_organisation_id'), table_name='intelligence_case_assumptions')
    op.drop_index(op.f('ix_intelligence_case_assumptions_case_id'), table_name='intelligence_case_assumptions')
    op.drop_table('intelligence_case_assumptions')
    op.drop_index(op.f('ix_intelligence_case_agent_findings_workspace_id'), table_name='intelligence_case_agent_findings')
    op.drop_index(op.f('ix_intelligence_case_agent_findings_status'), table_name='intelligence_case_agent_findings')
    op.drop_index(op.f('ix_intelligence_case_agent_findings_role'), table_name='intelligence_case_agent_findings')
    op.drop_index(op.f('ix_intelligence_case_agent_findings_organisation_id'), table_name='intelligence_case_agent_findings')
    op.drop_index(op.f('ix_intelligence_case_agent_findings_case_id'), table_name='intelligence_case_agent_findings')
    op.drop_index(op.f('ix_intelligence_case_agent_findings_agent_name'), table_name='intelligence_case_agent_findings')
    op.drop_table('intelligence_case_agent_findings')
    op.drop_index(op.f('ix_intelligence_cases_workspace_id'), table_name='intelligence_cases')
    op.drop_index(op.f('ix_intelligence_cases_website_id'), table_name='intelligence_cases')
    op.drop_index(op.f('ix_intelligence_cases_strategic_run_id'), table_name='intelligence_cases')
    op.drop_index(op.f('ix_intelligence_cases_status'), table_name='intelligence_cases')
    op.drop_index(op.f('ix_intelligence_cases_organisation_id'), table_name='intelligence_cases')
    op.drop_index(op.f('ix_intelligence_cases_created_by'), table_name='intelligence_cases')
    op.drop_table('intelligence_cases')
    # ### end Alembic commands ###
