"""Probabilistic AI Visibility controlled measurement

Revision ID: 0009_probabilistic_visibility
Revises: 0008_capability_profiles
Create Date: 2026-08-12
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0009_probabilistic_visibility"
down_revision: Union[str, None] = "0008_capability_profiles"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visibility_campaigns',
    sa.Column('website_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('target_repetitions', sa.Integer(), nullable=False),
    sa.Column('max_repetitions', sa.Integer(), nullable=False),
    sa.Column('max_calls_per_minute', sa.Integer(), nullable=False),
    sa.Column('max_concurrent', sa.Integer(), nullable=False),
    sa.Column('max_total_calls', sa.Integer(), nullable=False),
    sa.Column('min_interval_ms', sa.Integer(), nullable=False),
    sa.Column('campaign_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_visibility_campaigns_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_visibility_campaigns_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_visibility_campaigns_website_id_websites'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_visibility_campaigns_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visibility_campaigns'))
    )
    op.create_index(op.f('ix_visibility_campaigns_brand_name'), 'visibility_campaigns', ['brand_name'], unique=False)
    op.create_index(op.f('ix_visibility_campaigns_campaign_status'), 'visibility_campaigns', ['campaign_status'], unique=False)
    op.create_index(op.f('ix_visibility_campaigns_created_by'), 'visibility_campaigns', ['created_by'], unique=False)
    op.create_index(op.f('ix_visibility_campaigns_organisation_id'), 'visibility_campaigns', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_visibility_campaigns_status'), 'visibility_campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_visibility_campaigns_website_id'), 'visibility_campaigns', ['website_id'], unique=False)
    op.create_index(op.f('ix_visibility_campaigns_workspace_id'), 'visibility_campaigns', ['workspace_id'], unique=False)
    op.create_table('visibility_distributions',
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('metric_key', sa.String(length=64), nullable=False),
    sa.Column('subject_key', sa.String(length=128), nullable=False),
    sa.Column('scope_key', sa.String(length=128), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('variance', sa.Float(), nullable=False),
    sa.Column('ci_low', sa.Float(), nullable=False),
    sa.Column('ci_high', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('engine_disagreement', sa.Float(), nullable=False),
    sa.Column('temporal_volatility', sa.Float(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['visibility_campaigns.id'], name=op.f('fk_visibility_distributions_campaign_id_visibility_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_visibility_distributions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_visibility_distributions_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_visibility_distributions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visibility_distributions')),
    sa.UniqueConstraint('campaign_id', 'metric_key', 'subject_key', 'scope_key', name=op.f('uq_visibility_distributions_campaign_id'))
    )
    op.create_index(op.f('ix_visibility_distributions_campaign_id'), 'visibility_distributions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_visibility_distributions_created_by'), 'visibility_distributions', ['created_by'], unique=False)
    op.create_index(op.f('ix_visibility_distributions_metric_key'), 'visibility_distributions', ['metric_key'], unique=False)
    op.create_index(op.f('ix_visibility_distributions_organisation_id'), 'visibility_distributions', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_visibility_distributions_status'), 'visibility_distributions', ['status'], unique=False)
    op.create_index(op.f('ix_visibility_distributions_subject_key'), 'visibility_distributions', ['subject_key'], unique=False)
    op.create_index(op.f('ix_visibility_distributions_workspace_id'), 'visibility_distributions', ['workspace_id'], unique=False)
    op.create_table('visibility_probe_cells',
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('engine_code', sa.String(length=64), nullable=False),
    sa.Column('model_code', sa.String(length=128), nullable=True),
    sa.Column('location_code', sa.String(length=64), nullable=False),
    sa.Column('persona_code', sa.String(length=64), nullable=False),
    sa.Column('config_code', sa.String(length=64), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('time_bucket', sa.String(length=32), nullable=False),
    sa.Column('target_repetitions', sa.Integer(), nullable=False),
    sa.Column('completed_repetitions', sa.Integer(), nullable=False),
    sa.Column('generative_engine_id', sa.String(length=36), nullable=True),
    sa.Column('ai_query_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_query_id'], ['ai_queries.id'], name=op.f('fk_visibility_probe_cells_ai_query_id_ai_queries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['visibility_campaigns.id'], name=op.f('fk_visibility_probe_cells_campaign_id_visibility_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_visibility_probe_cells_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generative_engine_id'], ['generative_engines.id'], name=op.f('fk_visibility_probe_cells_generative_engine_id_generative_engines'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_visibility_probe_cells_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_visibility_probe_cells_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visibility_probe_cells')),
    sa.UniqueConstraint('campaign_id', 'prompt_hash', 'engine_code', 'location_code', 'persona_code', 'config_code', 'time_bucket', name=op.f('uq_visibility_probe_cells_campaign_id'))
    )
    op.create_index(op.f('ix_visibility_probe_cells_ai_query_id'), 'visibility_probe_cells', ['ai_query_id'], unique=False)
    op.create_index(op.f('ix_visibility_probe_cells_campaign_id'), 'visibility_probe_cells', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_visibility_probe_cells_config_code'), 'visibility_probe_cells', ['config_code'], unique=False)
    op.create_index(op.f('ix_visibility_probe_cells_created_by'), 'visibility_probe_cells', ['created_by'], unique=False)
    op.create_index(op.f('ix_visibility_probe_cells_engine_code'), 'visibility_probe_cells', ['engine_code'], unique=False)
    op.create_index(op.f('ix_visibility_probe_cells_generative_engine_id'), 'visibility_probe_cells', ['generative_engine_id'], unique=False)
    op.create_index(op.f('ix_visibility_probe_cells_location_code'), 'visibility_probe_cells', ['location_code'], unique=False)
    op.create_index(op.f('ix_visibility_probe_cells_organisation_id'), 'visibility_probe_cells', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_visibility_probe_cells_persona_code'), 'visibility_probe_cells', ['persona_code'], unique=False)
    op.create_index(op.f('ix_visibility_probe_cells_prompt_hash'), 'visibility_probe_cells', ['prompt_hash'], unique=False)
    op.create_index(op.f('ix_visibility_probe_cells_status'), 'visibility_probe_cells', ['status'], unique=False)
    op.create_index(op.f('ix_visibility_probe_cells_time_bucket'), 'visibility_probe_cells', ['time_bucket'], unique=False)
    op.create_index(op.f('ix_visibility_probe_cells_workspace_id'), 'visibility_probe_cells', ['workspace_id'], unique=False)
    op.create_table('visibility_score_cards',
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('website_id', sa.String(length=36), nullable=False),
    sa.Column('ai_visibility_score', sa.Float(), nullable=False),
    sa.Column('measurement_confidence', sa.String(length=16), nullable=False),
    sa.Column('peacock_visibility_confidence', sa.Float(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('engine_count', sa.Integer(), nullable=False),
    sa.Column('prompt_count', sa.Integer(), nullable=False),
    sa.Column('period_count', sa.Integer(), nullable=False),
    sa.Column('brand_mention_probability', sa.Float(), nullable=False),
    sa.Column('citation_probability', sa.Float(), nullable=False),
    sa.Column('top3_probability', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['visibility_campaigns.id'], name=op.f('fk_visibility_score_cards_campaign_id_visibility_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_visibility_score_cards_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_visibility_score_cards_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_visibility_score_cards_website_id_websites'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_visibility_score_cards_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visibility_score_cards'))
    )
    op.create_index(op.f('ix_visibility_score_cards_campaign_id'), 'visibility_score_cards', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_visibility_score_cards_computed_at'), 'visibility_score_cards', ['computed_at'], unique=False)
    op.create_index(op.f('ix_visibility_score_cards_created_by'), 'visibility_score_cards', ['created_by'], unique=False)
    op.create_index(op.f('ix_visibility_score_cards_measurement_confidence'), 'visibility_score_cards', ['measurement_confidence'], unique=False)
    op.create_index(op.f('ix_visibility_score_cards_organisation_id'), 'visibility_score_cards', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_visibility_score_cards_status'), 'visibility_score_cards', ['status'], unique=False)
    op.create_index(op.f('ix_visibility_score_cards_website_id'), 'visibility_score_cards', ['website_id'], unique=False)
    op.create_index(op.f('ix_visibility_score_cards_workspace_id'), 'visibility_score_cards', ['workspace_id'], unique=False)
    op.create_table('visibility_probe_observations',
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('cell_id', sa.String(length=36), nullable=False),
    sa.Column('run_index', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('brand_mentioned', sa.Boolean(), nullable=False),
    sa.Column('brand_cited', sa.Boolean(), nullable=False),
    sa.Column('brand_top3', sa.Boolean(), nullable=False),
    sa.Column('brand_position', sa.Integer(), nullable=True),
    sa.Column('competitor_mentions', sa.Text(), nullable=True),
    sa.Column('raw_excerpt', sa.Text(), nullable=True),
    sa.Column('structured_summary', sa.Text(), nullable=True),
    sa.Column('ai_query_run_id', sa.String(length=36), nullable=True),
    sa.Column('probe_source', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_query_run_id'], ['ai_query_runs.id'], name=op.f('fk_visibility_probe_observations_ai_query_run_id_ai_query_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['visibility_campaigns.id'], name=op.f('fk_visibility_probe_observations_campaign_id_visibility_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cell_id'], ['visibility_probe_cells.id'], name=op.f('fk_visibility_probe_observations_cell_id_visibility_probe_cells'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_visibility_probe_observations_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_visibility_probe_observations_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_visibility_probe_observations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visibility_probe_observations')),
    sa.UniqueConstraint('cell_id', 'run_index', name=op.f('uq_visibility_probe_observations_cell_id'))
    )
    op.create_index(op.f('ix_visibility_probe_observations_ai_query_run_id'), 'visibility_probe_observations', ['ai_query_run_id'], unique=False)
    op.create_index(op.f('ix_visibility_probe_observations_campaign_id'), 'visibility_probe_observations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_visibility_probe_observations_cell_id'), 'visibility_probe_observations', ['cell_id'], unique=False)
    op.create_index(op.f('ix_visibility_probe_observations_created_by'), 'visibility_probe_observations', ['created_by'], unique=False)
    op.create_index(op.f('ix_visibility_probe_observations_observed_at'), 'visibility_probe_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_visibility_probe_observations_organisation_id'), 'visibility_probe_observations', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_visibility_probe_observations_status'), 'visibility_probe_observations', ['status'], unique=False)
    op.create_index(op.f('ix_visibility_probe_observations_workspace_id'), 'visibility_probe_observations', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visibility_probe_observations_workspace_id'), table_name='visibility_probe_observations')
    op.drop_index(op.f('ix_visibility_probe_observations_status'), table_name='visibility_probe_observations')
    op.drop_index(op.f('ix_visibility_probe_observations_organisation_id'), table_name='visibility_probe_observations')
    op.drop_index(op.f('ix_visibility_probe_observations_observed_at'), table_name='visibility_probe_observations')
    op.drop_index(op.f('ix_visibility_probe_observations_created_by'), table_name='visibility_probe_observations')
    op.drop_index(op.f('ix_visibility_probe_observations_cell_id'), table_name='visibility_probe_observations')
    op.drop_index(op.f('ix_visibility_probe_observations_campaign_id'), table_name='visibility_probe_observations')
    op.drop_index(op.f('ix_visibility_probe_observations_ai_query_run_id'), table_name='visibility_probe_observations')
    op.drop_table('visibility_probe_observations')
    op.drop_index(op.f('ix_visibility_score_cards_workspace_id'), table_name='visibility_score_cards')
    op.drop_index(op.f('ix_visibility_score_cards_website_id'), table_name='visibility_score_cards')
    op.drop_index(op.f('ix_visibility_score_cards_status'), table_name='visibility_score_cards')
    op.drop_index(op.f('ix_visibility_score_cards_organisation_id'), table_name='visibility_score_cards')
    op.drop_index(op.f('ix_visibility_score_cards_measurement_confidence'), table_name='visibility_score_cards')
    op.drop_index(op.f('ix_visibility_score_cards_created_by'), table_name='visibility_score_cards')
    op.drop_index(op.f('ix_visibility_score_cards_computed_at'), table_name='visibility_score_cards')
    op.drop_index(op.f('ix_visibility_score_cards_campaign_id'), table_name='visibility_score_cards')
    op.drop_table('visibility_score_cards')
    op.drop_index(op.f('ix_visibility_probe_cells_workspace_id'), table_name='visibility_probe_cells')
    op.drop_index(op.f('ix_visibility_probe_cells_time_bucket'), table_name='visibility_probe_cells')
    op.drop_index(op.f('ix_visibility_probe_cells_status'), table_name='visibility_probe_cells')
    op.drop_index(op.f('ix_visibility_probe_cells_prompt_hash'), table_name='visibility_probe_cells')
    op.drop_index(op.f('ix_visibility_probe_cells_persona_code'), table_name='visibility_probe_cells')
    op.drop_index(op.f('ix_visibility_probe_cells_organisation_id'), table_name='visibility_probe_cells')
    op.drop_index(op.f('ix_visibility_probe_cells_location_code'), table_name='visibility_probe_cells')
    op.drop_index(op.f('ix_visibility_probe_cells_generative_engine_id'), table_name='visibility_probe_cells')
    op.drop_index(op.f('ix_visibility_probe_cells_engine_code'), table_name='visibility_probe_cells')
    op.drop_index(op.f('ix_visibility_probe_cells_created_by'), table_name='visibility_probe_cells')
    op.drop_index(op.f('ix_visibility_probe_cells_config_code'), table_name='visibility_probe_cells')
    op.drop_index(op.f('ix_visibility_probe_cells_campaign_id'), table_name='visibility_probe_cells')
    op.drop_index(op.f('ix_visibility_probe_cells_ai_query_id'), table_name='visibility_probe_cells')
    op.drop_table('visibility_probe_cells')
    op.drop_index(op.f('ix_visibility_distributions_workspace_id'), table_name='visibility_distributions')
    op.drop_index(op.f('ix_visibility_distributions_subject_key'), table_name='visibility_distributions')
    op.drop_index(op.f('ix_visibility_distributions_status'), table_name='visibility_distributions')
    op.drop_index(op.f('ix_visibility_distributions_organisation_id'), table_name='visibility_distributions')
    op.drop_index(op.f('ix_visibility_distributions_metric_key'), table_name='visibility_distributions')
    op.drop_index(op.f('ix_visibility_distributions_created_by'), table_name='visibility_distributions')
    op.drop_index(op.f('ix_visibility_distributions_campaign_id'), table_name='visibility_distributions')
    op.drop_table('visibility_distributions')
    op.drop_index(op.f('ix_visibility_campaigns_workspace_id'), table_name='visibility_campaigns')
    op.drop_index(op.f('ix_visibility_campaigns_website_id'), table_name='visibility_campaigns')
    op.drop_index(op.f('ix_visibility_campaigns_status'), table_name='visibility_campaigns')
    op.drop_index(op.f('ix_visibility_campaigns_organisation_id'), table_name='visibility_campaigns')
    op.drop_index(op.f('ix_visibility_campaigns_created_by'), table_name='visibility_campaigns')
    op.drop_index(op.f('ix_visibility_campaigns_campaign_status'), table_name='visibility_campaigns')
    op.drop_index(op.f('ix_visibility_campaigns_brand_name'), table_name='visibility_campaigns')
    op.drop_table('visibility_campaigns')
    # ### end Alembic commands ###
