"""Peacock Evidence Ledger relational graph

Revision ID: 0007_evidence_ledger
Revises: 0006_pine_intelligence_case
Create Date: 2026-08-12
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0007_evidence_ledger"
down_revision: Union[str, None] = "0006_pine_intelligence_case"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_evidences',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('freshness_hours', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('scope_kind', sa.String(length=64), nullable=False),
    sa.Column('scope_ref', sa.String(length=1024), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_unit', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('website_id', sa.String(length=36), nullable=True),
    sa.Column('crawl_id', sa.String(length=36), nullable=True),
    sa.Column('intelligence_case_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawls.id'], name=op.f('fk_ledger_evidences_crawl_id_crawls'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ledger_evidences_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['intelligence_case_id'], ['intelligence_cases.id'], name=op.f('fk_ledger_evidences_intelligence_case_id_intelligence_cases'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_ledger_evidences_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_ledger_evidences_website_id_websites'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ledger_evidences_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_evidences'))
    )
    op.create_index(op.f('ix_ledger_evidences_code'), 'ledger_evidences', ['code'], unique=False)
    op.create_index(op.f('ix_ledger_evidences_crawl_id'), 'ledger_evidences', ['crawl_id'], unique=False)
    op.create_index(op.f('ix_ledger_evidences_created_by'), 'ledger_evidences', ['created_by'], unique=False)
    op.create_index(op.f('ix_ledger_evidences_evidence_type'), 'ledger_evidences', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_ledger_evidences_intelligence_case_id'), 'ledger_evidences', ['intelligence_case_id'], unique=False)
    op.create_index(op.f('ix_ledger_evidences_observed_at'), 'ledger_evidences', ['observed_at'], unique=False)
    op.create_index(op.f('ix_ledger_evidences_organisation_id'), 'ledger_evidences', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_ledger_evidences_scope_kind'), 'ledger_evidences', ['scope_kind'], unique=False)
    op.create_index(op.f('ix_ledger_evidences_source'), 'ledger_evidences', ['source'], unique=False)
    op.create_index(op.f('ix_ledger_evidences_status'), 'ledger_evidences', ['status'], unique=False)
    op.create_index(op.f('ix_ledger_evidences_website_id'), 'ledger_evidences', ['website_id'], unique=False)
    op.create_index(op.f('ix_ledger_evidences_workspace_id'), 'ledger_evidences', ['workspace_id'], unique=False)
    op.create_table('ledger_findings',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('finding_kind', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=True),
    sa.Column('is_llm_derived', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('website_id', sa.String(length=36), nullable=True),
    sa.Column('intelligence_case_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ledger_findings_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['intelligence_case_id'], ['intelligence_cases.id'], name=op.f('fk_ledger_findings_intelligence_case_id_intelligence_cases'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_ledger_findings_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_ledger_findings_website_id_websites'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ledger_findings_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_findings'))
    )
    op.create_index(op.f('ix_ledger_findings_agent_name'), 'ledger_findings', ['agent_name'], unique=False)
    op.create_index(op.f('ix_ledger_findings_code'), 'ledger_findings', ['code'], unique=False)
    op.create_index(op.f('ix_ledger_findings_created_by'), 'ledger_findings', ['created_by'], unique=False)
    op.create_index(op.f('ix_ledger_findings_finding_kind'), 'ledger_findings', ['finding_kind'], unique=False)
    op.create_index(op.f('ix_ledger_findings_intelligence_case_id'), 'ledger_findings', ['intelligence_case_id'], unique=False)
    op.create_index(op.f('ix_ledger_findings_organisation_id'), 'ledger_findings', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_ledger_findings_severity'), 'ledger_findings', ['severity'], unique=False)
    op.create_index(op.f('ix_ledger_findings_status'), 'ledger_findings', ['status'], unique=False)
    op.create_index(op.f('ix_ledger_findings_website_id'), 'ledger_findings', ['website_id'], unique=False)
    op.create_index(op.f('ix_ledger_findings_workspace_id'), 'ledger_findings', ['workspace_id'], unique=False)
    op.create_table('ledger_claim_evidence_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('claim_kind', sa.String(length=64), nullable=False),
    sa.Column('claim_ref', sa.String(length=255), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=True),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['ledger_evidences.id'], name=op.f('fk_ledger_claim_evidence_links_evidence_id_ledger_evidences'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_ledger_claim_evidence_links_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ledger_claim_evidence_links_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_claim_evidence_links')),
    sa.UniqueConstraint('claim_kind', 'claim_ref', 'evidence_id', name=op.f('uq_ledger_claim_evidence_links_claim_kind'))
    )
    op.create_index(op.f('ix_ledger_claim_evidence_links_claim_kind'), 'ledger_claim_evidence_links', ['claim_kind'], unique=False)
    op.create_index(op.f('ix_ledger_claim_evidence_links_claim_ref'), 'ledger_claim_evidence_links', ['claim_ref'], unique=False)
    op.create_index(op.f('ix_ledger_claim_evidence_links_evidence_id'), 'ledger_claim_evidence_links', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_ledger_claim_evidence_links_organisation_id'), 'ledger_claim_evidence_links', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_ledger_claim_evidence_links_role'), 'ledger_claim_evidence_links', ['role'], unique=False)
    op.create_index(op.f('ix_ledger_claim_evidence_links_workspace_id'), 'ledger_claim_evidence_links', ['workspace_id'], unique=False)
    op.create_table('ledger_evidence_finding_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['ledger_evidences.id'], name=op.f('fk_ledger_evidence_finding_links_evidence_id_ledger_evidences'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['ledger_findings.id'], name=op.f('fk_ledger_evidence_finding_links_finding_id_ledger_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_ledger_evidence_finding_links_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ledger_evidence_finding_links_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_evidence_finding_links')),
    sa.UniqueConstraint('evidence_id', 'finding_id', name=op.f('uq_ledger_evidence_finding_links_evidence_id'))
    )
    op.create_index(op.f('ix_ledger_evidence_finding_links_evidence_id'), 'ledger_evidence_finding_links', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_ledger_evidence_finding_links_finding_id'), 'ledger_evidence_finding_links', ['finding_id'], unique=False)
    op.create_index(op.f('ix_ledger_evidence_finding_links_organisation_id'), 'ledger_evidence_finding_links', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_ledger_evidence_finding_links_role'), 'ledger_evidence_finding_links', ['role'], unique=False)
    op.create_index(op.f('ix_ledger_evidence_finding_links_workspace_id'), 'ledger_evidence_finding_links', ['workspace_id'], unique=False)
    op.create_table('ledger_recommendations',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('impact', sa.Float(), nullable=False),
    sa.Column('effort', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('website_id', sa.String(length=36), nullable=True),
    sa.Column('central_recommendation_id', sa.String(length=36), nullable=True),
    sa.Column('intelligence_case_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['central_recommendation_id'], ['recommendations.id'], name=op.f('fk_ledger_recommendations_central_recommendation_id_recommendations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ledger_recommendations_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['intelligence_case_id'], ['intelligence_cases.id'], name=op.f('fk_ledger_recommendations_intelligence_case_id_intelligence_cases'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_ledger_recommendations_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_ledger_recommendations_website_id_websites'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ledger_recommendations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_recommendations'))
    )
    op.create_index(op.f('ix_ledger_recommendations_central_recommendation_id'), 'ledger_recommendations', ['central_recommendation_id'], unique=False)
    op.create_index(op.f('ix_ledger_recommendations_code'), 'ledger_recommendations', ['code'], unique=False)
    op.create_index(op.f('ix_ledger_recommendations_created_by'), 'ledger_recommendations', ['created_by'], unique=False)
    op.create_index(op.f('ix_ledger_recommendations_intelligence_case_id'), 'ledger_recommendations', ['intelligence_case_id'], unique=False)
    op.create_index(op.f('ix_ledger_recommendations_organisation_id'), 'ledger_recommendations', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_ledger_recommendations_priority'), 'ledger_recommendations', ['priority'], unique=False)
    op.create_index(op.f('ix_ledger_recommendations_status'), 'ledger_recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_ledger_recommendations_website_id'), 'ledger_recommendations', ['website_id'], unique=False)
    op.create_index(op.f('ix_ledger_recommendations_workspace_id'), 'ledger_recommendations', ['workspace_id'], unique=False)
    op.create_table('ledger_actions',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_role', sa.String(length=64), nullable=True),
    sa.Column('success_metric', sa.String(length=255), nullable=True),
    sa.Column('action_status', sa.String(length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('website_id', sa.String(length=36), nullable=True),
    sa.Column('roadmap_task_id', sa.String(length=36), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ledger_actions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_id'], ['recommendation_executions.id'], name=op.f('fk_ledger_actions_execution_id_recommendation_executions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_ledger_actions_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_task_id'], ['roadmap_tasks.id'], name=op.f('fk_ledger_actions_roadmap_task_id_roadmap_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_ledger_actions_website_id_websites'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ledger_actions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_actions'))
    )
    op.create_index(op.f('ix_ledger_actions_action_status'), 'ledger_actions', ['action_status'], unique=False)
    op.create_index(op.f('ix_ledger_actions_code'), 'ledger_actions', ['code'], unique=False)
    op.create_index(op.f('ix_ledger_actions_created_by'), 'ledger_actions', ['created_by'], unique=False)
    op.create_index(op.f('ix_ledger_actions_execution_id'), 'ledger_actions', ['execution_id'], unique=False)
    op.create_index(op.f('ix_ledger_actions_organisation_id'), 'ledger_actions', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_ledger_actions_roadmap_task_id'), 'ledger_actions', ['roadmap_task_id'], unique=False)
    op.create_index(op.f('ix_ledger_actions_status'), 'ledger_actions', ['status'], unique=False)
    op.create_index(op.f('ix_ledger_actions_website_id'), 'ledger_actions', ['website_id'], unique=False)
    op.create_index(op.f('ix_ledger_actions_workspace_id'), 'ledger_actions', ['workspace_id'], unique=False)
    op.create_table('ledger_finding_recommendation_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['ledger_findings.id'], name=op.f('fk_ledger_finding_recommendation_links_finding_id_ledger_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_ledger_finding_recommendation_links_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['ledger_recommendations.id'], name=op.f('fk_ledger_finding_recommendation_links_recommendation_id_ledger_recommendations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ledger_finding_recommendation_links_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_finding_recommendation_links')),
    sa.UniqueConstraint('finding_id', 'recommendation_id', name=op.f('uq_ledger_finding_recommendation_links_finding_id'))
    )
    op.create_index(op.f('ix_ledger_finding_recommendation_links_finding_id'), 'ledger_finding_recommendation_links', ['finding_id'], unique=False)
    op.create_index(op.f('ix_ledger_finding_recommendation_links_organisation_id'), 'ledger_finding_recommendation_links', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_ledger_finding_recommendation_links_recommendation_id'), 'ledger_finding_recommendation_links', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_ledger_finding_recommendation_links_role'), 'ledger_finding_recommendation_links', ['role'], unique=False)
    op.create_index(op.f('ix_ledger_finding_recommendation_links_workspace_id'), 'ledger_finding_recommendation_links', ['workspace_id'], unique=False)
    op.create_table('ledger_outcomes',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('metric_key', sa.String(length=128), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome_kind', sa.String(length=64), nullable=False),
    sa.Column('website_id', sa.String(length=36), nullable=True),
    sa.Column('central_outcome_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['central_outcome_id'], ['recommendation_outcomes.id'], name=op.f('fk_ledger_outcomes_central_outcome_id_recommendation_outcomes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ledger_outcomes_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_ledger_outcomes_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_ledger_outcomes_website_id_websites'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ledger_outcomes_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_outcomes'))
    )
    op.create_index(op.f('ix_ledger_outcomes_central_outcome_id'), 'ledger_outcomes', ['central_outcome_id'], unique=False)
    op.create_index(op.f('ix_ledger_outcomes_code'), 'ledger_outcomes', ['code'], unique=False)
    op.create_index(op.f('ix_ledger_outcomes_created_by'), 'ledger_outcomes', ['created_by'], unique=False)
    op.create_index(op.f('ix_ledger_outcomes_metric_key'), 'ledger_outcomes', ['metric_key'], unique=False)
    op.create_index(op.f('ix_ledger_outcomes_observed_at'), 'ledger_outcomes', ['observed_at'], unique=False)
    op.create_index(op.f('ix_ledger_outcomes_organisation_id'), 'ledger_outcomes', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_ledger_outcomes_outcome_kind'), 'ledger_outcomes', ['outcome_kind'], unique=False)
    op.create_index(op.f('ix_ledger_outcomes_status'), 'ledger_outcomes', ['status'], unique=False)
    op.create_index(op.f('ix_ledger_outcomes_website_id'), 'ledger_outcomes', ['website_id'], unique=False)
    op.create_index(op.f('ix_ledger_outcomes_workspace_id'), 'ledger_outcomes', ['workspace_id'], unique=False)
    op.create_table('ledger_recommendation_action_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['ledger_actions.id'], name=op.f('fk_ledger_recommendation_action_links_action_id_ledger_actions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_ledger_recommendation_action_links_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['ledger_recommendations.id'], name=op.f('fk_ledger_recommendation_action_links_recommendation_id_ledger_recommendations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ledger_recommendation_action_links_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_recommendation_action_links')),
    sa.UniqueConstraint('recommendation_id', 'action_id', name=op.f('uq_ledger_recommendation_action_links_recommendation_id'))
    )
    op.create_index(op.f('ix_ledger_recommendation_action_links_action_id'), 'ledger_recommendation_action_links', ['action_id'], unique=False)
    op.create_index(op.f('ix_ledger_recommendation_action_links_organisation_id'), 'ledger_recommendation_action_links', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_ledger_recommendation_action_links_recommendation_id'), 'ledger_recommendation_action_links', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_ledger_recommendation_action_links_role'), 'ledger_recommendation_action_links', ['role'], unique=False)
    op.create_index(op.f('ix_ledger_recommendation_action_links_workspace_id'), 'ledger_recommendation_action_links', ['workspace_id'], unique=False)
    op.create_table('ledger_action_outcome_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('outcome_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['ledger_actions.id'], name=op.f('fk_ledger_action_outcome_links_action_id_ledger_actions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_ledger_action_outcome_links_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outcome_id'], ['ledger_outcomes.id'], name=op.f('fk_ledger_action_outcome_links_outcome_id_ledger_outcomes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ledger_action_outcome_links_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_action_outcome_links')),
    sa.UniqueConstraint('action_id', 'outcome_id', name=op.f('uq_ledger_action_outcome_links_action_id'))
    )
    op.create_index(op.f('ix_ledger_action_outcome_links_action_id'), 'ledger_action_outcome_links', ['action_id'], unique=False)
    op.create_index(op.f('ix_ledger_action_outcome_links_organisation_id'), 'ledger_action_outcome_links', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_ledger_action_outcome_links_outcome_id'), 'ledger_action_outcome_links', ['outcome_id'], unique=False)
    op.create_index(op.f('ix_ledger_action_outcome_links_role'), 'ledger_action_outcome_links', ['role'], unique=False)
    op.create_index(op.f('ix_ledger_action_outcome_links_workspace_id'), 'ledger_action_outcome_links', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_action_outcome_links_workspace_id'), table_name='ledger_action_outcome_links')
    op.drop_index(op.f('ix_ledger_action_outcome_links_role'), table_name='ledger_action_outcome_links')
    op.drop_index(op.f('ix_ledger_action_outcome_links_outcome_id'), table_name='ledger_action_outcome_links')
    op.drop_index(op.f('ix_ledger_action_outcome_links_organisation_id'), table_name='ledger_action_outcome_links')
    op.drop_index(op.f('ix_ledger_action_outcome_links_action_id'), table_name='ledger_action_outcome_links')
    op.drop_table('ledger_action_outcome_links')
    op.drop_index(op.f('ix_ledger_recommendation_action_links_workspace_id'), table_name='ledger_recommendation_action_links')
    op.drop_index(op.f('ix_ledger_recommendation_action_links_role'), table_name='ledger_recommendation_action_links')
    op.drop_index(op.f('ix_ledger_recommendation_action_links_recommendation_id'), table_name='ledger_recommendation_action_links')
    op.drop_index(op.f('ix_ledger_recommendation_action_links_organisation_id'), table_name='ledger_recommendation_action_links')
    op.drop_index(op.f('ix_ledger_recommendation_action_links_action_id'), table_name='ledger_recommendation_action_links')
    op.drop_table('ledger_recommendation_action_links')
    op.drop_index(op.f('ix_ledger_outcomes_workspace_id'), table_name='ledger_outcomes')
    op.drop_index(op.f('ix_ledger_outcomes_website_id'), table_name='ledger_outcomes')
    op.drop_index(op.f('ix_ledger_outcomes_status'), table_name='ledger_outcomes')
    op.drop_index(op.f('ix_ledger_outcomes_outcome_kind'), table_name='ledger_outcomes')
    op.drop_index(op.f('ix_ledger_outcomes_organisation_id'), table_name='ledger_outcomes')
    op.drop_index(op.f('ix_ledger_outcomes_observed_at'), table_name='ledger_outcomes')
    op.drop_index(op.f('ix_ledger_outcomes_metric_key'), table_name='ledger_outcomes')
    op.drop_index(op.f('ix_ledger_outcomes_created_by'), table_name='ledger_outcomes')
    op.drop_index(op.f('ix_ledger_outcomes_code'), table_name='ledger_outcomes')
    op.drop_index(op.f('ix_ledger_outcomes_central_outcome_id'), table_name='ledger_outcomes')
    op.drop_table('ledger_outcomes')
    op.drop_index(op.f('ix_ledger_finding_recommendation_links_workspace_id'), table_name='ledger_finding_recommendation_links')
    op.drop_index(op.f('ix_ledger_finding_recommendation_links_role'), table_name='ledger_finding_recommendation_links')
    op.drop_index(op.f('ix_ledger_finding_recommendation_links_recommendation_id'), table_name='ledger_finding_recommendation_links')
    op.drop_index(op.f('ix_ledger_finding_recommendation_links_organisation_id'), table_name='ledger_finding_recommendation_links')
    op.drop_index(op.f('ix_ledger_finding_recommendation_links_finding_id'), table_name='ledger_finding_recommendation_links')
    op.drop_table('ledger_finding_recommendation_links')
    op.drop_index(op.f('ix_ledger_actions_workspace_id'), table_name='ledger_actions')
    op.drop_index(op.f('ix_ledger_actions_website_id'), table_name='ledger_actions')
    op.drop_index(op.f('ix_ledger_actions_status'), table_name='ledger_actions')
    op.drop_index(op.f('ix_ledger_actions_roadmap_task_id'), table_name='ledger_actions')
    op.drop_index(op.f('ix_ledger_actions_organisation_id'), table_name='ledger_actions')
    op.drop_index(op.f('ix_ledger_actions_execution_id'), table_name='ledger_actions')
    op.drop_index(op.f('ix_ledger_actions_created_by'), table_name='ledger_actions')
    op.drop_index(op.f('ix_ledger_actions_code'), table_name='ledger_actions')
    op.drop_index(op.f('ix_ledger_actions_action_status'), table_name='ledger_actions')
    op.drop_table('ledger_actions')
    op.drop_index(op.f('ix_ledger_recommendations_workspace_id'), table_name='ledger_recommendations')
    op.drop_index(op.f('ix_ledger_recommendations_website_id'), table_name='ledger_recommendations')
    op.drop_index(op.f('ix_ledger_recommendations_status'), table_name='ledger_recommendations')
    op.drop_index(op.f('ix_ledger_recommendations_priority'), table_name='ledger_recommendations')
    op.drop_index(op.f('ix_ledger_recommendations_organisation_id'), table_name='ledger_recommendations')
    op.drop_index(op.f('ix_ledger_recommendations_intelligence_case_id'), table_name='ledger_recommendations')
    op.drop_index(op.f('ix_ledger_recommendations_created_by'), table_name='ledger_recommendations')
    op.drop_index(op.f('ix_ledger_recommendations_code'), table_name='ledger_recommendations')
    op.drop_index(op.f('ix_ledger_recommendations_central_recommendation_id'), table_name='ledger_recommendations')
    op.drop_table('ledger_recommendations')
    op.drop_index(op.f('ix_ledger_evidence_finding_links_workspace_id'), table_name='ledger_evidence_finding_links')
    op.drop_index(op.f('ix_ledger_evidence_finding_links_role'), table_name='ledger_evidence_finding_links')
    op.drop_index(op.f('ix_ledger_evidence_finding_links_organisation_id'), table_name='ledger_evidence_finding_links')
    op.drop_index(op.f('ix_ledger_evidence_finding_links_finding_id'), table_name='ledger_evidence_finding_links')
    op.drop_index(op.f('ix_ledger_evidence_finding_links_evidence_id'), table_name='ledger_evidence_finding_links')
    op.drop_table('ledger_evidence_finding_links')
    op.drop_index(op.f('ix_ledger_claim_evidence_links_workspace_id'), table_name='ledger_claim_evidence_links')
    op.drop_index(op.f('ix_ledger_claim_evidence_links_role'), table_name='ledger_claim_evidence_links')
    op.drop_index(op.f('ix_ledger_claim_evidence_links_organisation_id'), table_name='ledger_claim_evidence_links')
    op.drop_index(op.f('ix_ledger_claim_evidence_links_evidence_id'), table_name='ledger_claim_evidence_links')
    op.drop_index(op.f('ix_ledger_claim_evidence_links_claim_ref'), table_name='ledger_claim_evidence_links')
    op.drop_index(op.f('ix_ledger_claim_evidence_links_claim_kind'), table_name='ledger_claim_evidence_links')
    op.drop_table('ledger_claim_evidence_links')
    op.drop_index(op.f('ix_ledger_findings_workspace_id'), table_name='ledger_findings')
    op.drop_index(op.f('ix_ledger_findings_website_id'), table_name='ledger_findings')
    op.drop_index(op.f('ix_ledger_findings_status'), table_name='ledger_findings')
    op.drop_index(op.f('ix_ledger_findings_severity'), table_name='ledger_findings')
    op.drop_index(op.f('ix_ledger_findings_organisation_id'), table_name='ledger_findings')
    op.drop_index(op.f('ix_ledger_findings_intelligence_case_id'), table_name='ledger_findings')
    op.drop_index(op.f('ix_ledger_findings_finding_kind'), table_name='ledger_findings')
    op.drop_index(op.f('ix_ledger_findings_created_by'), table_name='ledger_findings')
    op.drop_index(op.f('ix_ledger_findings_code'), table_name='ledger_findings')
    op.drop_index(op.f('ix_ledger_findings_agent_name'), table_name='ledger_findings')
    op.drop_table('ledger_findings')
    op.drop_index(op.f('ix_ledger_evidences_workspace_id'), table_name='ledger_evidences')
    op.drop_index(op.f('ix_ledger_evidences_website_id'), table_name='ledger_evidences')
    op.drop_index(op.f('ix_ledger_evidences_status'), table_name='ledger_evidences')
    op.drop_index(op.f('ix_ledger_evidences_source'), table_name='ledger_evidences')
    op.drop_index(op.f('ix_ledger_evidences_scope_kind'), table_name='ledger_evidences')
    op.drop_index(op.f('ix_ledger_evidences_organisation_id'), table_name='ledger_evidences')
    op.drop_index(op.f('ix_ledger_evidences_observed_at'), table_name='ledger_evidences')
    op.drop_index(op.f('ix_ledger_evidences_intelligence_case_id'), table_name='ledger_evidences')
    op.drop_index(op.f('ix_ledger_evidences_evidence_type'), table_name='ledger_evidences')
    op.drop_index(op.f('ix_ledger_evidences_created_by'), table_name='ledger_evidences')
    op.drop_index(op.f('ix_ledger_evidences_crawl_id'), table_name='ledger_evidences')
    op.drop_index(op.f('ix_ledger_evidences_code'), table_name='ledger_evidences')
    op.drop_table('ledger_evidences')
    # ### end Alembic commands ###
