"""Dynamic model capability profiles for PINE routing

Revision ID: 0008_capability_profiles
Revises: 0007_evidence_ledger
Create Date: 2026-08-12
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0008_capability_profiles"
down_revision: Union[str, None] = "0007_evidence_ledger"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_capability_priors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_code', sa.String(length=64), nullable=False),
    sa.Column('model_code', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('cost_usd_micros', sa.Integer(), nullable=False),
    sa.Column('failure_rate', sa.Float(), nullable=False),
    sa.Column('json_compliance_rate', sa.Float(), nullable=False),
    sa.Column('citation_accuracy', sa.Float(), nullable=False),
    sa.Column('historical_agreement', sa.Float(), nullable=False),
    sa.Column('prior_weight', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_capability_priors')),
    sa.UniqueConstraint('provider_code', 'model_code', 'task_type', name=op.f('uq_model_capability_priors_provider_code'))
    )
    op.create_index(op.f('ix_model_capability_priors_model_code'), 'model_capability_priors', ['model_code'], unique=False)
    op.create_index(op.f('ix_model_capability_priors_provider_code'), 'model_capability_priors', ['provider_code'], unique=False)
    op.create_index(op.f('ix_model_capability_priors_task_type'), 'model_capability_priors', ['task_type'], unique=False)
    op.create_table('model_capability_profiles',
    sa.Column('provider_code', sa.String(length=64), nullable=False),
    sa.Column('model_code', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('latency_ms_avg', sa.Float(), nullable=False),
    sa.Column('cost_usd_micros_avg', sa.Float(), nullable=False),
    sa.Column('failure_rate', sa.Float(), nullable=False),
    sa.Column('json_compliance_rate', sa.Float(), nullable=False),
    sa.Column('citation_accuracy', sa.Float(), nullable=False),
    sa.Column('historical_agreement', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_model_capability_profiles_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['ai_provider_models.id'], name=op.f('fk_model_capability_profiles_model_id_ai_provider_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_model_capability_profiles_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], name=op.f('fk_model_capability_profiles_provider_id_ai_providers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_model_capability_profiles_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_capability_profiles')),
    sa.UniqueConstraint('workspace_id', 'provider_code', 'model_code', 'task_type', name=op.f('uq_model_capability_profiles_workspace_id'))
    )
    op.create_index(op.f('ix_model_capability_profiles_created_by'), 'model_capability_profiles', ['created_by'], unique=False)
    op.create_index(op.f('ix_model_capability_profiles_model_code'), 'model_capability_profiles', ['model_code'], unique=False)
    op.create_index(op.f('ix_model_capability_profiles_model_id'), 'model_capability_profiles', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_capability_profiles_organisation_id'), 'model_capability_profiles', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_model_capability_profiles_provider_code'), 'model_capability_profiles', ['provider_code'], unique=False)
    op.create_index(op.f('ix_model_capability_profiles_provider_id'), 'model_capability_profiles', ['provider_id'], unique=False)
    op.create_index(op.f('ix_model_capability_profiles_status'), 'model_capability_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_model_capability_profiles_task_type'), 'model_capability_profiles', ['task_type'], unique=False)
    op.create_index(op.f('ix_model_capability_profiles_workspace_id'), 'model_capability_profiles', ['workspace_id'], unique=False)
    op.create_table('model_capability_observations',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('provider_code', sa.String(length=64), nullable=False),
    sa.Column('model_code', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('cost_usd_micros', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('json_compliant', sa.Boolean(), nullable=True),
    sa.Column('citation_accuracy', sa.Float(), nullable=True),
    sa.Column('historical_agreement', sa.Float(), nullable=True),
    sa.Column('gateway_role', sa.String(length=64), nullable=True),
    sa.Column('template_id', sa.String(length=128), nullable=True),
    sa.Column('llm_request_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_model_capability_observations_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['llm_request_id'], ['llm_requests.id'], name=op.f('fk_model_capability_observations_llm_request_id_llm_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_model_capability_observations_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['model_capability_profiles.id'], name=op.f('fk_model_capability_observations_profile_id_model_capability_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_model_capability_observations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_capability_observations'))
    )
    op.create_index(op.f('ix_model_capability_observations_created_by'), 'model_capability_observations', ['created_by'], unique=False)
    op.create_index(op.f('ix_model_capability_observations_gateway_role'), 'model_capability_observations', ['gateway_role'], unique=False)
    op.create_index(op.f('ix_model_capability_observations_llm_request_id'), 'model_capability_observations', ['llm_request_id'], unique=False)
    op.create_index(op.f('ix_model_capability_observations_model_code'), 'model_capability_observations', ['model_code'], unique=False)
    op.create_index(op.f('ix_model_capability_observations_organisation_id'), 'model_capability_observations', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_model_capability_observations_profile_id'), 'model_capability_observations', ['profile_id'], unique=False)
    op.create_index(op.f('ix_model_capability_observations_provider_code'), 'model_capability_observations', ['provider_code'], unique=False)
    op.create_index(op.f('ix_model_capability_observations_status'), 'model_capability_observations', ['status'], unique=False)
    op.create_index(op.f('ix_model_capability_observations_task_type'), 'model_capability_observations', ['task_type'], unique=False)
    op.create_index(op.f('ix_model_capability_observations_workspace_id'), 'model_capability_observations', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_capability_observations_workspace_id'), table_name='model_capability_observations')
    op.drop_index(op.f('ix_model_capability_observations_task_type'), table_name='model_capability_observations')
    op.drop_index(op.f('ix_model_capability_observations_status'), table_name='model_capability_observations')
    op.drop_index(op.f('ix_model_capability_observations_provider_code'), table_name='model_capability_observations')
    op.drop_index(op.f('ix_model_capability_observations_profile_id'), table_name='model_capability_observations')
    op.drop_index(op.f('ix_model_capability_observations_organisation_id'), table_name='model_capability_observations')
    op.drop_index(op.f('ix_model_capability_observations_model_code'), table_name='model_capability_observations')
    op.drop_index(op.f('ix_model_capability_observations_llm_request_id'), table_name='model_capability_observations')
    op.drop_index(op.f('ix_model_capability_observations_gateway_role'), table_name='model_capability_observations')
    op.drop_index(op.f('ix_model_capability_observations_created_by'), table_name='model_capability_observations')
    op.drop_table('model_capability_observations')
    op.drop_index(op.f('ix_model_capability_profiles_workspace_id'), table_name='model_capability_profiles')
    op.drop_index(op.f('ix_model_capability_profiles_task_type'), table_name='model_capability_profiles')
    op.drop_index(op.f('ix_model_capability_profiles_status'), table_name='model_capability_profiles')
    op.drop_index(op.f('ix_model_capability_profiles_provider_id'), table_name='model_capability_profiles')
    op.drop_index(op.f('ix_model_capability_profiles_provider_code'), table_name='model_capability_profiles')
    op.drop_index(op.f('ix_model_capability_profiles_organisation_id'), table_name='model_capability_profiles')
    op.drop_index(op.f('ix_model_capability_profiles_model_id'), table_name='model_capability_profiles')
    op.drop_index(op.f('ix_model_capability_profiles_model_code'), table_name='model_capability_profiles')
    op.drop_index(op.f('ix_model_capability_profiles_created_by'), table_name='model_capability_profiles')
    op.drop_table('model_capability_profiles')
    op.drop_index(op.f('ix_model_capability_priors_task_type'), table_name='model_capability_priors')
    op.drop_index(op.f('ix_model_capability_priors_provider_code'), table_name='model_capability_priors')
    op.drop_index(op.f('ix_model_capability_priors_model_code'), table_name='model_capability_priors')
    op.drop_table('model_capability_priors')
    # ### end Alembic commands ###
