"""SQLAlchemy models — multi-tenant Peacock One core database."""

from db_models.audit import AuditLog, AuditLogAttribute
from db_models.audits import (
    Audit,
    AuditIssue,
    AuditMetric,
    AuditRecommendation,
    AuditSection,
)
from db_models.base import (
    Base,
    OrganisationScopedMixin,
    TimestampMixin,
    WorkspaceTenantMixin,
    new_uuid,
)
from db_models.capability_profiles import (
    CAPABILITY_TASK_TYPES,
    ModelCapabilityObservation,
    ModelCapabilityPrior,
    ModelCapabilityProfile,
)
from db_models.citation_graph import (
    CIS_COMPONENTS,
    FORBIDDEN_TACTICS,
    OPPORTUNITY_TYPES,
    PATHWAY_NODE_KINDS,
    SOURCE_CLASSES,
    CitationGraphAnalysis,
    CgCitation,
    CgDomainScore,
    CgEntityMention,
    CgObservation,
    CgPathway,
    CgSourceOpportunity,
)
from db_models.retrieval_pathway import (
    BOTTLENECK_STAGES,
    FORENSIC_CAUSES,
    LIKELIHOOD_BANDS,
    METHODOLOGY_DISCLAIMER,
    UNCERTAINTY_BANDS,
    RetrievalPathwayAnalysis,
    RpiBottleneckDiagnosis,
    RpiCauseClassification,
    RpiEvidence,
)
from db_models.entity_intelligence import (
    ASSOCIATION_COMPONENTS,
    ENTITY_TYPES,
    STRATEGY_ACTIONS,
    EntityIntelligenceAnalysis,
    EiAssociation,
    EiEntity,
    EiEntityGap,
    EiStrategy,
)
from db_models.deep_competitor import (
    COMPETITOR_CATEGORIES,
    CONTENT_COMPARE_DIMENSIONS,
    DISCOVERY_SIGNALS,
    FORBIDDEN_RECOMMENDATION_MODES,
    DeepCompetitorAnalysis,
    DcCompetitiveDelta,
    DcCompetitorProfile,
    DcContentDiff,
    DcDifferentiatedStrategy,
)
from db_models.content_lab import (
    CITABILITY_COMPONENTS,
    CITABILITY_DISCLAIMER,
    INFO_GAIN_PENALTIES,
    INFO_GAIN_REWARDS,
    MOAT_FORMAT_PRIORS,
    OPPORTUNITY_DIMENSIONS,
    ClCitabilityComponent,
    ClContentProposal,
    ClInfoGainSignal,
    ContentLabAnalysis,
)
from db_models.content_digital_twin import (
    FINDING_CATEGORIES,
    METHODOLOGY as CONTENT_DIGITAL_TWIN_METHODOLOGY,
    METHODOLOGY_NOTE as CONTENT_DIGITAL_TWIN_METHODOLOGY_NOTE,
    SIMULATION_SURFACES,
    CdtEvaluation,
    CdtFinding,
    CdtRequirementScore,
    ContentDigitalTwin,
)
from db_models.geo_lab import (
    CAUSALITY_LEVELS,
    CAUSALITY_WARNING,
    GEO_LAB_METRICS,
    METHODOLOGY as GEO_LAB_METHODOLOGY,
    METHODOLOGY_NOTE as GEO_LAB_METHODOLOGY_NOTE,
    PAGE_ROLES,
    VARIANT_CODES,
    VARIANT_PRESETS,
    GlCausalityAssessment,
    GlMetricDelta,
    GlMetricObservation,
    GlPage,
    GlVariant,
    GeoLabExperiment,
)
from db_models.writer_intelligence import (
    METHODOLOGY as WRITER_INTELLIGENCE_METHODOLOGY,
    METHODOLOGY_NOTE as WRITER_INTELLIGENCE_METHODOLOGY_NOTE,
    OUTCOME_EDGE_TYPES,
    OUTCOME_NODE_KINDS,
    PERFORMANCE_METRICS as WRITER_PERFORMANCE_METRICS,
    SIMILARITY_ONLY_REJECTED,
    WRITER_DNA_TRAITS,
    WiDnaTrait,
    WiOutcomeEdge,
    WiOutcomeNode,
    WiPerformanceRecord,
    WiRecommendation,
    WiWriterDna,
    WriterIntelligenceAnalysis,
)
from db_models.opportunity_engine import (
    ALWAYS_ON_NOTE,
    DEFAULT_RANKING_WEIGHTS,
    METHODOLOGY as OPPORTUNITY_ENGINE_METHODOLOGY,
    METHODOLOGY_NOTE as OPPORTUNITY_ENGINE_METHODOLOGY_NOTE,
    OPPORTUNITY_TYPES,
    RANKING_FEATURES,
    OpportunityScan,
    PeacockOpportunity,
    PoEvidence,
    PoOutcomeFeedback,
    PoRankingFactor,
    PoRankingWeight,
)
from db_models.council2 import (
    COUNCIL_ROLES,
    DEBATE_ROUNDS,
    FORBIDDEN_PROMPTS,
    FORBIDDEN_STORAGE_FIELDS,
    METHODOLOGY as COUNCIL2_METHODOLOGY,
    METHODOLOGY_NOTE as COUNCIL2_METHODOLOGY_NOTE,
    ROLE_MANDATES,
    STORED_ARTIFACT_KINDS,
    C2Agent,
    C2Claim,
    C2Counterargument,
    C2Decision,
    C2Disagreement,
    C2Evidence,
    C2EvidenceRequest,
    C2RoundRecord,
    Council2Session,
)
from db_models.judge2 import (
    DEFAULT_JUDGE_WEIGHTS,
    JUDGE_SIGNAL_FAMILIES,
    METHODOLOGY as JUDGE2_METHODOLOGY,
    METHODOLOGY_NOTE as JUDGE2_METHODOLOGY_NOTE,
    SCORING_OUTSIDE_LLM,
    J2Evidence,
    J2ReversalCondition,
    J2SignalScore,
    Judge2Judgment,
)
from db_models.scenario_engine import (
    DEFAULT_METRIC as SCENARIO_DEFAULT_METRIC,
    DEFAULT_METRIC_LABEL as SCENARIO_DEFAULT_METRIC_LABEL,
    METHODOLOGY as SCENARIO_METHODOLOGY,
    METHODOLOGY_NOTE as SCENARIO_METHODOLOGY_NOTE,
    RANGES_NOT_FAKE_PRECISION as SCENARIO_RANGES_NOT_FAKE_PRECISION,
    STRATEGY_CODES as SCENARIO_STRATEGY_CODES,
    STRATEGY_LABELS as SCENARIO_STRATEGY_LABELS,
    ScenarioAnalysis,
    SeAssumption,
    SeMetricRange,
    SeScenario,
)
from db_models.peacock90 import (
    CAPACITY_GUARDRAIL as PEACOCK90_CAPACITY_GUARDRAIL,
    HORIZON_DAYS as PEACOCK90_HORIZON_DAYS,
    METHODOLOGY as PEACOCK90_METHODOLOGY,
    METHODOLOGY_NOTE as PEACOCK90_METHODOLOGY_NOTE,
    PRIORITY_CODES as PEACOCK90_PRIORITY_CODES,
    RISK_TOLERANCE_LEVELS as PEACOCK90_RISK_TOLERANCE_LEVELS,
    TASK_KINDS as PEACOCK90_TASK_KINDS,
    P90CapacityRefusal,
    P90Dependency,
    P90Initiative,
    P90Task,
    Peacock90Plan,
)
from db_models.competitors import (
    Competitor,
    CompetitorContent,
    CompetitorGap,
    CompetitorMetric,
    CompetitorWebsite,
)
from db_models.content import (
    BacklinkOpportunity,
    CitationSource,
    ContentBrief,
    ContentRecommendation,
    Keyword,
    KeywordCluster,
    Topic,
    TopicCluster,
    TopicRecommendation,
)
from db_models.crawls import Crawl, CrawlIssue, CrawlLink, CrawlPage
from db_models.embeddings import EmbeddingChunk, EmbeddingChunkAttribute
from db_models.evidence_ledger import (
    EVIDENCE_TYPES,
    LedgerAction,
    LedgerActionOutcomeLink,
    LedgerClaimEvidenceLink,
    LedgerEvidence,
    LedgerEvidenceFindingLink,
    LedgerFinding,
    LedgerFindingRecommendationLink,
    LedgerOutcome,
    LedgerRecommendation,
    LedgerRecommendationActionLink,
)
from db_models.geo_aeo import (
    AEOObservation,
    AIQuery,
    AIQueryRun,
    AIResponseObservation,
    AIVisibilitySnapshot,
    BrandMention,
    CitationObservation,
    EntityObservation,
    GEOMetric,
    GenerativeEngine,
)
from db_models.identity import (
    Membership,
    Organisation,
    Permission,
    Role,
    RolePermission,
    User,
    Workspace,
    WorkspaceMembership,
)
from db_models.intelligence_case import (
    IntelligenceCaseAgentClaim,
    IntelligenceCaseAgentFinding,
    IntelligenceCaseAssumption,
    IntelligenceCaseContextItem,
    IntelligenceCaseContradiction,
    IntelligenceCaseEvidence,
    IntelligenceCaseEvidenceUrl,
    IntelligenceCaseHypothesis,
    IntelligenceCaseModelUsed,
    IntelligenceCaseObservation,
    IntelligenceCaseOpportunity,
    IntelligenceCaseRecommendation,
    IntelligenceCaseRecommendationEvidence,
    IntelligenceCaseRecord,
    IntelligenceCaseRisk,
    IntelligenceCaseToolUsed,
    IntelligenceCaseUnknown,
)
from db_models.jobs import BackgroundJob
from db_models.learning import (
    FeatureWeight,
    ModelEvaluation,
    Recommendation,
    RecommendationExecution,
    RecommendationMetric,
    RecommendationOutcome,
)
from db_models.llm_intelligence import (
    AgentResult,
    AgentRun,
    CouncilRun,
    Decision,
    Evidence,
    LLMRequest,
    LLMResponse,
)
from db_models.monitoring import (
    MetricSnapshot,
    MonitoringProject,
    SearchPerformanceSnapshot,
)
from db_models.providers import AiProvider, AiProviderModel
from db_models.probabilistic_visibility import (
    VisibilityCampaign,
    VisibilityDistribution,
    VisibilityProbeCell,
    VisibilityProbeObservation,
    VisibilityScoreCard,
)
from db_models.prompt_universe import (
    FUNNEL_STAGES,
    PROMPT_SOURCE_KINDS,
    PROMPT_TYPES,
    SYNTHETIC_PERSONA_SEEDS,
    PromptFamily,
    PromptGenerationRun,
    PromptSourceSignal,
    PromptUniverse,
    SyntheticPersona,
    UniversePrompt,
)
from db_models.share_of_answer import (
    COMPARISON_OUTCOMES,
    SOA_INDICATORS,
    ShareOfAnswerAnalysis,
    SoaAnswerObservation,
    SoaBrandScore,
    SoaEntityIndicator,
)
from db_models.roadmaps import (
    Roadmap,
    RoadmapMonth,
    RoadmapRecommendation,
    RoadmapTask,
    RoadmapWeek,
)
from db_models.seo import (
    InternalLinkResult,
    OnPageSEOResult,
    PerformanceResult,
    SchemaResult,
    SEOScore,
    TechnicalSEOResult,
)
from db_models.websites import Domain, Website, WebsiteProperty
from db_models.writers import (
    Writer,
    WriterAssignment,
    WriterIndustryExpertise,
    WriterPerformance,
    WriterProfile,
    WriterRecommendation,
    WriterSample,
    WriterSkill,
)

# Naming aliases requested by product vocabulary
Organization = Organisation
LLMProvider = AiProvider
LLMModel = AiProviderModel

__all__ = [
    "AEOObservation",
    "AIQuery",
    "AIQueryRun",
    "AIResponseObservation",
    "AIVisibilitySnapshot",
    "AgentResult",
    "AgentRun",
    "AiProvider",
    "AiProviderModel",
    "Audit",
    "AuditIssue",
    "AuditLog",
    "AuditLogAttribute",
    "AuditMetric",
    "AuditRecommendation",
    "AuditSection",
    "BacklinkOpportunity",
    "BackgroundJob",
    "Base",
    "BrandMention",
    "CITABILITY_COMPONENTS",
    "CITABILITY_DISCLAIMER",
    "ClCitabilityComponent",
    "ClContentProposal",
    "ClInfoGainSignal",
    "ContentLabAnalysis",
    "CONTENT_DIGITAL_TWIN_METHODOLOGY",
    "CONTENT_DIGITAL_TWIN_METHODOLOGY_NOTE",
    "ContentDigitalTwin",
    "CdtEvaluation",
    "CdtFinding",
    "CdtRequirementScore",
    "FINDING_CATEGORIES",
    "SIMULATION_SURFACES",
    "CAUSALITY_LEVELS",
    "CAUSALITY_WARNING",
    "GEO_LAB_METRICS",
    "GEO_LAB_METHODOLOGY",
    "GEO_LAB_METHODOLOGY_NOTE",
    "PAGE_ROLES",
    "VARIANT_CODES",
    "VARIANT_PRESETS",
    "GeoLabExperiment",
    "GlCausalityAssessment",
    "GlMetricDelta",
    "GlMetricObservation",
    "GlPage",
    "GlVariant",
    "WRITER_DNA_TRAITS",
    "WRITER_INTELLIGENCE_METHODOLOGY",
    "WRITER_INTELLIGENCE_METHODOLOGY_NOTE",
    "WRITER_PERFORMANCE_METRICS",
    "OUTCOME_EDGE_TYPES",
    "OUTCOME_NODE_KINDS",
    "SIMILARITY_ONLY_REJECTED",
    "WriterIntelligenceAnalysis",
    "WiDnaTrait",
    "WiOutcomeEdge",
    "WiOutcomeNode",
    "WiPerformanceRecord",
    "WiRecommendation",
    "WiWriterDna",
    "ALWAYS_ON_NOTE",
    "DEFAULT_RANKING_WEIGHTS",
    "OPPORTUNITY_ENGINE_METHODOLOGY",
    "OPPORTUNITY_ENGINE_METHODOLOGY_NOTE",
    "OPPORTUNITY_TYPES",
    "RANKING_FEATURES",
    "OpportunityScan",
    "PeacockOpportunity",
    "PoEvidence",
    "PoOutcomeFeedback",
    "PoRankingFactor",
    "PoRankingWeight",
    "COUNCIL_ROLES",
    "DEBATE_ROUNDS",
    "FORBIDDEN_PROMPTS",
    "FORBIDDEN_STORAGE_FIELDS",
    "COUNCIL2_METHODOLOGY",
    "COUNCIL2_METHODOLOGY_NOTE",
    "ROLE_MANDATES",
    "STORED_ARTIFACT_KINDS",
    "Council2Session",
    "C2Agent",
    "C2Claim",
    "C2Counterargument",
    "C2Decision",
    "C2Disagreement",
    "C2Evidence",
    "C2EvidenceRequest",
    "C2RoundRecord",
    "DEFAULT_JUDGE_WEIGHTS",
    "JUDGE_SIGNAL_FAMILIES",
    "JUDGE2_METHODOLOGY",
    "JUDGE2_METHODOLOGY_NOTE",
    "SCORING_OUTSIDE_LLM",
    "Judge2Judgment",
    "J2Evidence",
    "J2ReversalCondition",
    "J2SignalScore",
    "SCENARIO_DEFAULT_METRIC",
    "SCENARIO_DEFAULT_METRIC_LABEL",
    "SCENARIO_METHODOLOGY",
    "SCENARIO_METHODOLOGY_NOTE",
    "SCENARIO_RANGES_NOT_FAKE_PRECISION",
    "SCENARIO_STRATEGY_CODES",
    "SCENARIO_STRATEGY_LABELS",
    "ScenarioAnalysis",
    "SeAssumption",
    "SeMetricRange",
    "SeScenario",
    "PEACOCK90_CAPACITY_GUARDRAIL",
    "PEACOCK90_HORIZON_DAYS",
    "PEACOCK90_METHODOLOGY",
    "PEACOCK90_METHODOLOGY_NOTE",
    "PEACOCK90_PRIORITY_CODES",
    "PEACOCK90_RISK_TOLERANCE_LEVELS",
    "PEACOCK90_TASK_KINDS",
    "Peacock90Plan",
    "P90CapacityRefusal",
    "P90Dependency",
    "P90Initiative",
    "P90Task",
    "INFO_GAIN_PENALTIES",
    "INFO_GAIN_REWARDS",
    "MOAT_FORMAT_PRIORS",
    "OPPORTUNITY_DIMENSIONS",
    "ASSOCIATION_COMPONENTS",
    "BOTTLENECK_STAGES",
    "CAPABILITY_TASK_TYPES",
    "CIS_COMPONENTS",
    "COMPETITOR_CATEGORIES",
    "CONTENT_COMPARE_DIMENSIONS",
    "CitationGraphAnalysis",
    "CitationObservation",
    "CitationSource",
    "CgCitation",
    "CgDomainScore",
    "CgEntityMention",
    "CgObservation",
    "CgPathway",
    "CgSourceOpportunity",
    "DISCOVERY_SIGNALS",
    "DeepCompetitorAnalysis",
    "DcCompetitiveDelta",
    "DcCompetitorProfile",
    "DcContentDiff",
    "DcDifferentiatedStrategy",
    "ENTITY_TYPES",
    "EntityIntelligenceAnalysis",
    "EiAssociation",
    "EiEntity",
    "EiEntityGap",
    "EiStrategy",
    "FORBIDDEN_RECOMMENDATION_MODES",
    "FORENSIC_CAUSES",
    "FORBIDDEN_TACTICS",
    "LIKELIHOOD_BANDS",
    "METHODOLOGY_DISCLAIMER",
    "RetrievalPathwayAnalysis",
    "RpiBottleneckDiagnosis",
    "RpiCauseClassification",
    "RpiEvidence",
    "STRATEGY_ACTIONS",
    "UNCERTAINTY_BANDS",
    "Competitor",
    "CompetitorContent",
    "CompetitorGap",
    "CompetitorMetric",
    "CompetitorWebsite",
    "ContentBrief",
    "ContentRecommendation",
    "CouncilRun",
    "Crawl",
    "CrawlIssue",
    "CrawlLink",
    "CrawlPage",
    "Decision",
    "Domain",
    "EVIDENCE_TYPES",
    "EmbeddingChunk",
    "EmbeddingChunkAttribute",
    "EntityObservation",
    "Evidence",
    "FeatureWeight",
    "ModelCapabilityObservation",
    "ModelCapabilityPrior",
    "ModelCapabilityProfile",
    "LedgerAction",
    "LedgerActionOutcomeLink",
    "LedgerClaimEvidenceLink",
    "LedgerEvidence",
    "LedgerEvidenceFindingLink",
    "LedgerFinding",
    "LedgerFindingRecommendationLink",
    "LedgerOutcome",
    "LedgerRecommendation",
    "LedgerRecommendationActionLink",
    "GEOMetric",
    "GenerativeEngine",
    "IntelligenceCaseAgentClaim",
    "IntelligenceCaseAgentFinding",
    "IntelligenceCaseAssumption",
    "IntelligenceCaseContextItem",
    "IntelligenceCaseContradiction",
    "IntelligenceCaseEvidence",
    "IntelligenceCaseEvidenceUrl",
    "IntelligenceCaseHypothesis",
    "IntelligenceCaseModelUsed",
    "IntelligenceCaseObservation",
    "IntelligenceCaseOpportunity",
    "IntelligenceCaseRecommendation",
    "IntelligenceCaseRecommendationEvidence",
    "IntelligenceCaseRecord",
    "IntelligenceCaseRisk",
    "IntelligenceCaseToolUsed",
    "IntelligenceCaseUnknown",
    "InternalLinkResult",
    "Keyword",
    "KeywordCluster",
    "LLMModel",
    "LLMProvider",
    "LLMRequest",
    "LLMResponse",
    "Membership",
    "MetricSnapshot",
    "ModelEvaluation",
    "MonitoringProject",
    "OPPORTUNITY_TYPES",
    "OnPageSEOResult",
    "Organisation",
    "OrganisationScopedMixin",
    "Organization",
    "PATHWAY_NODE_KINDS",
    "PerformanceResult",
    "Permission",
    "FUNNEL_STAGES",
    "PROMPT_SOURCE_KINDS",
    "PROMPT_TYPES",
    "SYNTHETIC_PERSONA_SEEDS",
    "PromptFamily",
    "PromptGenerationRun",
    "PromptSourceSignal",
    "PromptUniverse",
    "SOURCE_CLASSES",
    "SyntheticPersona",
    "UniversePrompt",
    "VisibilityCampaign",
    "VisibilityDistribution",
    "VisibilityProbeCell",
    "VisibilityProbeObservation",
    "VisibilityScoreCard",
    "Recommendation",
    "RecommendationExecution",
    "RecommendationMetric",
    "RecommendationOutcome",
    "Roadmap",
    "RoadmapMonth",
    "RoadmapRecommendation",
    "RoadmapTask",
    "RoadmapWeek",
    "Role",
    "RolePermission",
    "SEOScore",
    "SchemaResult",
    "SearchPerformanceSnapshot",
    "COMPARISON_OUTCOMES",
    "SOA_INDICATORS",
    "ShareOfAnswerAnalysis",
    "SoaAnswerObservation",
    "SoaBrandScore",
    "SoaEntityIndicator",
    "TechnicalSEOResult",
    "TimestampMixin",
    "Topic",
    "TopicCluster",
    "TopicRecommendation",
    "User",
    "Website",
    "WebsiteProperty",
    "Workspace",
    "WorkspaceMembership",
    "WorkspaceTenantMixin",
    "Writer",
    "WriterAssignment",
    "WriterIndustryExpertise",
    "WriterPerformance",
    "WriterProfile",
    "WriterRecommendation",
    "WriterSample",
    "WriterSkill",
    "new_uuid",
]
