import type { Permission } from "@/permissions/types";
import type { ReportCategory, ReportDefinition } from "@/modules/reports/types";

export type { ReportCategory };

function def(
  partial: Omit<ReportDefinition, "exportable"> & { exportable?: boolean },
): ReportDefinition {
  return { exportable: true, ...partial };
}

export const REPORT_CATALOG: ReportDefinition[] = [
  // Company
  def({
    key: "company.revenue-trend",
    title: "Revenue trend",
    category: "company",
    description: "Invoiced revenue by day in the selected range.",
    permission: "reports:view",
    extraPermissions: ["finance:view"],
    revenueDefinition: "invoiced",
    chartType: "line",
  }),
  def({
    key: "company.collected-revenue-trend",
    title: "Collected-revenue trend",
    category: "company",
    description: "Payments received over time.",
    permission: "reports:view",
    extraPermissions: ["finance:view"],
    revenueDefinition: "collected",
    chartType: "line",
  }),
  def({
    key: "company.pipeline-forecast",
    title: "Pipeline forecast",
    category: "company",
    description: "Open pipeline weighted by stage probability.",
    permission: "reports:view",
    extraPermissions: ["crm:view"],
    revenueDefinition: "closed",
    chartType: "bar",
  }),
  def({
    key: "company.revenue-versus-target",
    title: "Revenue versus target",
    category: "company",
    description: "Closed achievement against sales targets.",
    permission: "reports:view",
    extraPermissions: ["sales:view"],
    revenueDefinition: "closed",
    chartType: "bar",
  }),
  def({
    key: "company.revenue-by-service",
    title: "Revenue by service",
    category: "company",
    description: "Project service mix as a revenue proxy.",
    permission: "reports:view",
    extraPermissions: ["projects:view"],
    revenueDefinition: "invoiced",
    chartType: "bar",
  }),
  def({
    key: "company.revenue-by-client",
    title: "Revenue by client",
    category: "company",
    description: "Invoiced totals by client company.",
    permission: "reports:view",
    extraPermissions: ["finance:view"],
    revenueDefinition: "invoiced",
    chartType: "bar",
  }),
  def({
    key: "company.client-concentration",
    title: "Client concentration",
    category: "company",
    description: "Share of invoiced revenue by top clients.",
    permission: "reports:view",
    extraPermissions: ["finance:view"],
    revenueDefinition: "invoiced",
    chartType: "bar",
  }),
  def({
    key: "company.client-retention",
    title: "Client retention",
    category: "company",
    description: "Clients invoiced in prior period that remain active.",
    permission: "reports:view",
    extraPermissions: ["crm:view"],
    chartType: "table",
  }),
  def({
    key: "company.project-profitability",
    title: "Project profitability",
    category: "company",
    description: "Latest profitability snapshots by project.",
    permission: "reports:view",
    extraPermissions: ["finance:view_profitability"],
    chartType: "table",
    restrictedExportFields: ["costMinor", "profitMinor", "marginPct"],
  }),
  def({
    key: "company.department-performance",
    title: "Department performance",
    category: "company",
    description: "Department objective progress.",
    permission: "reports:view",
    chartType: "bar",
  }),
  def({
    key: "company.objective-progress",
    title: "Company objective progress",
    category: "company",
    description: "Company-scoped objectives and completion.",
    permission: "reports:view",
    chartType: "table",
  }),
  def({
    key: "company.headcount-trend",
    title: "Headcount trend",
    category: "company",
    description: "Active headcount by joining cohort in range.",
    permission: "reports:view",
    extraPermissions: ["hr:view"],
    chartType: "line",
  }),
  def({
    key: "company.attendance-trend",
    title: "Attendance trend",
    category: "company",
    description: "Present / WFH counts by day.",
    permission: "reports:view",
    extraPermissions: ["hr:view"],
    chartType: "line",
  }),
  def({
    key: "company.expense-trend",
    title: "Expense trend",
    category: "company",
    description: "Approved and pending expenses by day.",
    permission: "reports:view",
    extraPermissions: ["finance:view"],
    chartType: "line",
  }),
  def({
    key: "company.receivable-aging",
    title: "Receivable aging",
    category: "company",
    description: "Outstanding invoice balances by age bucket.",
    permission: "reports:view",
    extraPermissions: ["finance:view"],
    revenueDefinition: "invoiced",
    chartType: "bar",
  }),
  def({
    key: "company.cash-collection",
    title: "Cash collection",
    category: "company",
    description: "Collected payments in the selected range.",
    permission: "reports:view",
    extraPermissions: ["finance:view"],
    revenueDefinition: "collected",
    chartType: "line",
  }),
  def({
    key: "company.monthly-business-summary",
    title: "Monthly business summary",
    category: "company",
    description: "Snapshot of growth, delivery, people, and cash.",
    permission: "reports:view",
    chartType: "table",
  }),

  // CRM
  def({
    key: "crm.leads-by-source",
    title: "Leads by source",
    category: "crm",
    description: "New leads grouped by source.",
    permission: "crm:view",
    chartType: "bar",
  }),
  def({
    key: "crm.leads-by-campaign",
    title: "Leads by campaign",
    category: "crm",
    description: "New leads grouped by campaign.",
    permission: "crm:view",
    chartType: "bar",
  }),
  def({
    key: "crm.leads-by-service",
    title: "Leads by service",
    category: "crm",
    description: "Lead interest services (JSON tags).",
    permission: "crm:view",
    chartType: "bar",
  }),
  def({
    key: "crm.leads-by-country",
    title: "Leads by country",
    category: "crm",
    description: "New leads by country.",
    permission: "crm:view",
    chartType: "bar",
  }),
  def({
    key: "crm.leads-by-salesperson",
    title: "Leads by salesperson",
    category: "crm",
    description: "Assigned lead volume by owner.",
    permission: "crm:view",
    chartType: "bar",
  }),
  def({
    key: "crm.funnel-conversion",
    title: "Funnel conversion",
    category: "crm",
    description: "Open deals counted by pipeline stage.",
    permission: "crm:view",
    chartType: "bar",
  }),
  def({
    key: "crm.stage-aging",
    title: "Stage aging",
    category: "crm",
    description: "Average days open deals have sat in each stage.",
    permission: "crm:view",
    chartType: "bar",
  }),
  def({
    key: "crm.win-rate",
    title: "Win rate",
    category: "crm",
    description: "Won deals as a share of closed deals.",
    permission: "crm:view",
    revenueDefinition: "closed",
    chartType: "table",
  }),
  def({
    key: "crm.loss-reasons",
    title: "Loss reasons",
    category: "crm",
    description: "Closed-lost deals by reason.",
    permission: "crm:view",
    chartType: "bar",
  }),
  def({
    key: "crm.average-deal-size",
    title: "Average deal size",
    category: "crm",
    description: "Average won deal value.",
    permission: "crm:view",
    revenueDefinition: "closed",
    chartType: "table",
  }),
  def({
    key: "crm.sales-cycle-length",
    title: "Sales-cycle length",
    category: "crm",
    description: "Average days from create to close for won deals.",
    permission: "crm:view",
    chartType: "table",
  }),
  def({
    key: "crm.follow-up-compliance",
    title: "Follow-up compliance",
    category: "crm",
    description: "Completed versus overdue follow-ups.",
    permission: "crm:view",
    chartType: "bar",
  }),
  def({
    key: "crm.forecast-accuracy",
    title: "Forecast accuracy",
    category: "crm",
    description: "Weighted pipeline versus closed won in range.",
    permission: "crm:view",
    revenueDefinition: "closed",
    chartType: "table",
  }),

  // Sales
  def({
    key: "sales.target-versus-achievement",
    title: "Target versus achievement",
    category: "sales",
    description: "Sales targets compared to recorded achievement.",
    permission: "sales:view",
    revenueDefinition: "closed",
    chartType: "bar",
  }),
  def({
    key: "sales.revenue-by-salesperson",
    title: "Revenue by salesperson",
    category: "sales",
    description: "Closed attribution by salesperson.",
    permission: "sales:view",
    revenueDefinition: "closed",
    chartType: "bar",
  }),
  def({
    key: "sales.collected-by-salesperson",
    title: "Collected revenue by salesperson",
    category: "sales",
    description: "Collected attribution by salesperson.",
    permission: "sales:view",
    revenueDefinition: "collected",
    chartType: "bar",
  }),
  def({
    key: "sales.cost-versus-revenue",
    title: "Cost-versus-revenue ratio",
    category: "sales",
    description: "Monthly cost against attributed revenue.",
    permission: "sales:view",
    extraPermissions: ["employees:view_compensation"],
    chartType: "table",
    restrictedExportFields: ["costMinor", "ratio"],
  }),
  def({
    key: "sales.consecutive-negative-months",
    title: "Consecutive negative-month status",
    category: "sales",
    description: "Employees with consecutive months where cost exceeds revenue.",
    permission: "sales:view",
    extraPermissions: ["employees:view_compensation"],
    chartType: "table",
    restrictedExportFields: ["costMinor", "revenueMinor"],
  }),
  def({
    key: "sales.leaderboard",
    title: "Sales leaderboard",
    category: "sales",
    description: "Ranked achievement for the period.",
    permission: "sales:view",
    revenueDefinition: "closed",
    chartType: "table",
  }),
  def({
    key: "sales.commission-estimate",
    title: "Commission estimate",
    category: "sales",
    description: "Commission records in the selected months.",
    permission: "sales:view",
    chartType: "table",
    restrictedExportFields: ["commissionMinor", "baseMinor"],
  }),
  def({
    key: "sales.deals-sourced",
    title: "Deals sourced",
    category: "sales",
    description: "Sourced revenue attributions.",
    permission: "sales:view",
    revenueDefinition: "sourced",
    chartType: "bar",
  }),
  def({
    key: "sales.deals-closed",
    title: "Deals closed",
    category: "sales",
    description: "Closed revenue attributions.",
    permission: "sales:view",
    revenueDefinition: "closed",
    chartType: "bar",
  }),
  def({
    key: "sales.assisted-revenue",
    title: "Assisted revenue",
    category: "sales",
    description: "Assisted revenue attributions.",
    permission: "sales:view",
    revenueDefinition: "sourced",
    chartType: "bar",
  }),
  def({
    key: "sales.attribution-breakdown",
    title: "Revenue attribution breakdown",
    category: "sales",
    description: "Attribution mix by type.",
    permission: "sales:view",
    chartType: "bar",
  }),

  // XYME
  def({
    key: "xyme.completion-company",
    title: "XYME completion by company",
    category: "xyme",
    description: "Average goal progress across the company.",
    permission: "xyme:view",
    chartType: "table",
  }),
  def({
    key: "xyme.completion-department",
    title: "XYME completion by department",
    category: "xyme",
    description: "Average XYME progress by department.",
    permission: "xyme:view",
    chartType: "bar",
  }),
  def({
    key: "xyme.completion-manager",
    title: "XYME completion by manager",
    category: "xyme",
    description: "Team XYME progress rolled up to managers.",
    permission: "xyme:view",
    chartType: "bar",
  }),
  def({
    key: "xyme.average-x",
    title: "Average X score",
    category: "xyme",
    description: "Mean progress for X-category goals.",
    permission: "xyme:view",
    chartType: "table",
  }),
  def({
    key: "xyme.average-y",
    title: "Average Y score",
    category: "xyme",
    description: "Mean progress for Y-category goals.",
    permission: "xyme:view",
    chartType: "table",
  }),
  def({
    key: "xyme.average-me",
    title: "Average ME score",
    category: "xyme",
    description: "Mean progress for ME-category goals.",
    permission: "xyme:view",
    chartType: "table",
  }),
  def({
    key: "xyme.approval-turnaround",
    title: "Goal approval turnaround time",
    category: "xyme",
    description: "Average hours from plan submit to approval decision.",
    permission: "xyme:view",
    chartType: "table",
  }),
  def({
    key: "xyme.missing-check-ins",
    title: "Missing check-ins",
    category: "xyme",
    description: "Approved plans without a check-in in the last 7 days.",
    permission: "xyme:view",
    chartType: "table",
  }),
  def({
    key: "xyme.qoq-trend",
    title: "Quarter-over-quarter trend",
    category: "xyme",
    description: "Average XYME progress by active cycle.",
    permission: "xyme:view",
    chartType: "bar",
  }),
  def({
    key: "xyme.employee-drilldown",
    title: "Employee-level XYME drill-down",
    category: "xyme",
    description: "Per-employee goal progress (permission scoped).",
    permission: "xyme:view",
    chartType: "table",
  }),

  // HR
  def({
    key: "hr.headcount",
    title: "Headcount",
    category: "hr",
    description: "Active employment headcount.",
    permission: "hr:view",
    chartType: "table",
  }),
  def({
    key: "hr.department-distribution",
    title: "Department distribution",
    category: "hr",
    description: "Headcount by department.",
    permission: "hr:view",
    chartType: "bar",
  }),
  def({
    key: "hr.employment-type",
    title: "Employment type",
    category: "hr",
    description: "Headcount by employment type.",
    permission: "hr:view",
    chartType: "bar",
  }),
  def({
    key: "hr.attendance",
    title: "Attendance",
    category: "hr",
    description: "Attendance status counts in range.",
    permission: "hr:view",
    chartType: "bar",
  }),
  def({
    key: "hr.late-arrivals",
    title: "Late arrivals",
    category: "hr",
    description: "Attendance rows marked late.",
    permission: "hr:view",
    chartType: "table",
  }),
  def({
    key: "hr.absence",
    title: "Absence",
    category: "hr",
    description: "Absent / leave attendance statuses.",
    permission: "hr:view",
    chartType: "bar",
  }),
  def({
    key: "hr.leave-utilization",
    title: "Leave utilization",
    category: "hr",
    description: "Approved leave days versus balances.",
    permission: "hr:view",
    chartType: "table",
  }),
  def({
    key: "hr.attrition",
    title: "Attrition",
    category: "hr",
    description: "Employees exited in the selected range.",
    permission: "hr:view",
    chartType: "table",
  }),
  def({
    key: "hr.probation-completion",
    title: "Probation completion",
    category: "hr",
    description: "Probation end dates falling in range.",
    permission: "hr:view",
    chartType: "table",
  }),
  def({
    key: "hr.recruitment-funnel",
    title: "Recruitment funnel",
    category: "hr",
    description: "Candidate applications by stage.",
    permission: "hr:view",
    chartType: "bar",
  }),
  def({
    key: "hr.time-to-hire",
    title: "Time to hire",
    category: "hr",
    description: "Average days from application to offer acceptance.",
    permission: "hr:view",
    chartType: "table",
  }),
  def({
    key: "hr.onboarding-completion",
    title: "Onboarding completion",
    category: "hr",
    description: "Onboarding checklist completion rates.",
    permission: "hr:view",
    chartType: "table",
  }),
  def({
    key: "hr.asset-allocation",
    title: "Asset allocation",
    category: "hr",
    description: "Currently assigned company assets.",
    permission: "hr:view",
    chartType: "table",
  }),
  def({
    key: "hr.document-expiry",
    title: "Document expiry",
    category: "hr",
    description: "Employee documents expiring in the next 60 days.",
    permission: "hr:view",
    chartType: "table",
  }),

  // Delivery
  def({
    key: "delivery.active-projects",
    title: "Active projects",
    category: "delivery",
    description: "Projects in active delivery statuses.",
    permission: "projects:view",
    chartType: "table",
  }),
  def({
    key: "delivery.project-health",
    title: "Project health",
    category: "delivery",
    description: "Projects by health/status.",
    permission: "projects:view",
    chartType: "bar",
  }),
  def({
    key: "delivery.on-time-delivery",
    title: "On-time delivery",
    category: "delivery",
    description: "Milestones completed on or before due date.",
    permission: "projects:view",
    chartType: "table",
  }),
  def({
    key: "delivery.overdue-deliverables",
    title: "Overdue deliverables",
    category: "delivery",
    description: "Deliverables past due and not completed.",
    permission: "projects:view",
    chartType: "table",
  }),
  def({
    key: "delivery.revision-rate",
    title: "Revision rate",
    category: "delivery",
    description: "Average deliverable versions per deliverable.",
    permission: "projects:view",
    chartType: "table",
  }),
  def({
    key: "delivery.employee-utilization",
    title: "Employee utilization",
    category: "delivery",
    description: "Resource allocation percentages.",
    permission: "projects:view",
    chartType: "bar",
  }),
  def({
    key: "delivery.billable-utilization",
    title: "Billable utilization",
    category: "delivery",
    description: "Billable hours as a share of total hours.",
    permission: "projects:view",
    chartType: "table",
  }),
  def({
    key: "delivery.capacity",
    title: "Capacity",
    category: "delivery",
    description: "Allocated capacity versus team size.",
    permission: "projects:view",
    chartType: "table",
  }),
  def({
    key: "delivery.timesheet-compliance",
    title: "Timesheet compliance",
    category: "delivery",
    description: "Employees with time entries in range.",
    permission: "projects:view",
    chartType: "table",
  }),
  def({
    key: "delivery.budget-versus-actual",
    title: "Budget versus actual",
    category: "delivery",
    description: "Project budgets compared to cost snapshots.",
    permission: "projects:view",
    extraPermissions: ["finance:view_profitability"],
    chartType: "table",
    restrictedExportFields: ["costMinor", "budgetMinor"],
  }),
  def({
    key: "delivery.margin",
    title: "Margin",
    category: "delivery",
    description: "Project margin from profitability snapshots.",
    permission: "projects:view",
    extraPermissions: ["finance:view_profitability"],
    chartType: "table",
    restrictedExportFields: ["marginPct", "profitMinor"],
  }),
  def({
    key: "delivery.client-feedback",
    title: "Client feedback",
    category: "delivery",
    description: "Deliverable approval outcomes as feedback proxy.",
    permission: "projects:view",
    chartType: "bar",
  }),

  // Finance
  def({
    key: "finance.invoiced-revenue",
    title: "Invoiced revenue",
    category: "finance",
    description: "Non-draft invoices issued in range.",
    permission: "finance:view",
    revenueDefinition: "invoiced",
    chartType: "table",
  }),
  def({
    key: "finance.collected-revenue",
    title: "Collected revenue",
    category: "finance",
    description: "Payments received in range.",
    permission: "finance:view",
    revenueDefinition: "collected",
    chartType: "table",
  }),
  def({
    key: "finance.outstanding-receivables",
    title: "Outstanding receivables",
    category: "finance",
    description: "Open invoice balances.",
    permission: "finance:view",
    revenueDefinition: "invoiced",
    chartType: "table",
  }),
  def({
    key: "finance.aging-buckets",
    title: "Aging buckets",
    category: "finance",
    description: "Receivable aging buckets.",
    permission: "finance:view",
    chartType: "bar",
  }),
  def({
    key: "finance.overdue-invoices",
    title: "Overdue invoices",
    category: "finance",
    description: "Invoices past due with remaining balance.",
    permission: "finance:view",
    chartType: "table",
  }),
  def({
    key: "finance.payment-trend",
    title: "Payment trend",
    category: "finance",
    description: "Daily collected payments.",
    permission: "finance:view",
    revenueDefinition: "collected",
    chartType: "line",
  }),
  def({
    key: "finance.expenses-by-category",
    title: "Expenses by category",
    category: "finance",
    description: "Expense totals by category.",
    permission: "finance:view",
    chartType: "bar",
  }),
  def({
    key: "finance.vendor-spend",
    title: "Vendor spend",
    category: "finance",
    description: "Vendor bill totals.",
    permission: "finance:view",
    chartType: "bar",
  }),
  def({
    key: "finance.project-margin",
    title: "Project margin",
    category: "finance",
    description: "Margin by project.",
    permission: "finance:view_profitability",
    chartType: "table",
    restrictedExportFields: ["marginPct", "costMinor", "profitMinor"],
  }),
  def({
    key: "finance.client-profitability",
    title: "Client profitability",
    category: "finance",
    description: "Revenue and cost roll-up by client.",
    permission: "finance:view_profitability",
    chartType: "table",
    restrictedExportFields: ["costMinor", "profitMinor", "marginPct"],
  }),
  def({
    key: "finance.service-profitability",
    title: "Service profitability",
    category: "finance",
    description: "Service mix profitability proxy.",
    permission: "finance:view_profitability",
    chartType: "table",
    restrictedExportFields: ["costMinor", "profitMinor"],
  }),
];

const byKey = new Map(REPORT_CATALOG.map((item) => [item.key, item]));

export function getReportDefinition(key: string): ReportDefinition | undefined {
  return byKey.get(key);
}

export function reportsForCategory(category: ReportCategory): ReportDefinition[] {
  return REPORT_CATALOG.filter((item) => item.category === category);
}

export function categoryLabel(category: ReportCategory): string {
  switch (category) {
    case "company":
      return "Company";
    case "crm":
      return "CRM";
    case "sales":
      return "Sales";
    case "xyme":
      return "XYME";
    case "hr":
      return "HR";
    case "delivery":
      return "Delivery";
    case "finance":
      return "Finance";
  }
}

export function visibleCatalog(
  has: (permission: Permission) => boolean,
): ReportDefinition[] {
  return REPORT_CATALOG.filter((item) => {
    if (!has(item.permission)) return false;
    return (item.extraPermissions ?? []).every((permission) => has(permission));
  });
}
